WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint12a_V1.1/objects/Route_Schedule__c.object
<CustomObject>
</CustomObject>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>SeqNbr__c</fullName>
        <label>SeqNbr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>StopDate__c</fullName>
        <label>StopDate</label>
        <type>Date</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_02a_V1.3/objects/User.object
<CustomObject>
</CustomObject>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_02a_V1.3/classes/AB_UsersAndAccountsDetailsService_Test.cls
@isTest
public class AB_UsersAndAccountsDetailsService_Test {
    public static string strJSONBody;
    static testMethod void UnitTest1() {
       Recordtype WholesalerRType = [select id ,name from recordtype where sobjecttype = 'account' and name ='Wholesaler'];
       Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
       account objAc = new account();
       objAc.name = 'Test Account';       
       objAc.recordtypeid = POCRtype.id;
       insert objAc;
       
       account objAcWhole = new account();
       objAcWhole.name = 'Test Account';       
       objAcWhole.recordtypeid = WholesalerRType.id;
       objAcWhole.WSLR_NBR_US__c = '123';
       insert objAcWhole;
       
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
        User usr = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '123',
             WSLRNbrRouteNbr__c = '4556',
             IsActive = true
             );
             insert usr;
       strJSONBody = '{\"username\":\"'+usr.Username+'\",\"accountid\":\"'+objAc.id+'\"}';
       Route__c objRte = new Route__c();
       objRte.WSLRNbrRouteNbr__c = '4556';
       insert objRte;
       
       Route_Schedule__c route = new Route_Schedule__c();
       route.Route__c = objRte.id;
       route.SeqNbr__c = 1;
       route.Account__C = objAc.id;
       //route.Schedule_Date__c = system.today();
       route.StopDate__c = System.today();
       //route.Sales_Rep__c = usr;
       insert route;
       
       AccountTeamMember objAteam = new AccountTeamMember ();
       objAteam.UserId = usr.id;
       objAteam.TeamMemberRole = 'BAM';
       objAteam.AccountAccessLevel = 'Edit';
       objAteam.CaseAccessLevel = 'Edit'; 
       objAteam.OpportunityAccessLevel = 'Edit';
       objAteam.AccountId =objAc.id;       
       insert objAteam;
       
       AB_UsersAndAccountsDetailsService.AB_UsersAndAccountsDetailsService();
       AB_UsersAndAccountsDetailsService.UserDetailsWrapper objWrap = new AB_UsersAndAccountsDetailsService.UserDetailsWrapper('','');
    }
    static testMethod void UnitTest2() {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
        User usr = new User(LastName = 'LIVESTON',FirstName='JASON',Alias = 'jliv',Email = 'jason.liveston@asdf.com',Username = 'jason.lieston@asp.com',ProfileId = profileId.id,           
             TimeZoneSidKey = 'GMT',LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US',Wholesaler_Number__c = '123',WSLRNbrRouteNbr__c = '4556',IsActive = true
             );
             insert usr;
        strJSONBody = '{\"username\":\"'+usr.Username+'\"}';
       User usr2 = new User(LastName = 'LIVESTON2',FirstName='JASON2',Alias = 'jliv2',Email = 'jason.liveston2@asdf.com',Username = 'jason.lieston2@asp.com',ProfileId = profileId.id,           
             TimeZoneSidKey = 'GMT',LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US',Wholesaler_Number__c = '123',WSLRNbrRouteNbr__c = '4556',IsActive = true
             );
             insert usr2;      
        
        AB_UsersAndAccountsDetailsService.AB_UsersAndAccountsDetailsService();
    }
}