WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

WOD_Sprint11a_V1.1/objects/Account.object
    <fields>
        <fullName>Trade_Program_NM__c</fullName>
        <label>Trade Program NM</label>
        <length>100</length>
        <type>Text</type>
    </fields>

MOBcombined/objects/Account.object
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field displays the wholesaler that services this Retailer</inlineHelpText>
        <label>Wholesaler</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers Served</relationshipLabel>
        <relationshipName>Retailer_Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint12a_V1.1/objects/Route_Schedule__c.object
<CustomObject>
</CustomObject>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>SeqNbr__c</fullName>
        <label>SeqNbr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>StopDate__c</fullName>
        <label>StopDate</label>
        <type>Date</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_02a_V1.3/objects/User.object
<CustomObject>
</CustomObject>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_02a_V1.3/classes/AB_salesExcelleceTrg_Test.cls
@isTest
public class AB_salesExcelleceTrg_Test {
     static testMethod void UnitTest() {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User usr1 = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '10500',
             WSLRNbrRouteNbr__c = '0D010093143'
             );
             insert usr1;
         
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
        account objAc = new account();
       objAc.name = 'Test Account';       
       objAc.recordtypeid = POCRtype.id;
       //objAc.billingCity = '';
       objAc.billingstate = 'THyderabad';
       //objAc.billingCountry = 'Hyderabad';
       //objAc.billingPostalCode = '500459';
       objAc.Trade_Program_NM__c = 'MACRO';
       //objAc.Wholesaler__c = objAcWhole.id;
       objAc.INDUS_VOL_CLASS_CD_US__c = '20';
       insert objAc;
        
        event objEve  =  new event();
        objEve.subject = 'Test Event';
        objEve.Visit_in_Progress__c = false;
        objEve.Visit_Completed__c = true;
        objEve.OwnerId = usr1.id;
        objEve.Whatid = objAc.id;
        objEve.ActivityDateTime = system.today();
        objEve.DurationInMinutes = 30;
        objEve.Out_of_Range_on_End__c = true;
        //objEve.Out_of_Range_on_Start__c = false;
        //objEve.createddate = system.today();
        insert objEve;  
        
        objEve.Out_of_Range_on_Start__c = true;
        //objEve.createddate = system.today();
        //update objEve; 
        
        Route__c objRte = new Route__c();
        objRte.WSLRNbrRouteNbr__c = '0D010093143';      
        insert objRte; 
        
        Route_Schedule__c route = new Route_Schedule__c();
        route.Route__c = objRte.id;
        route.SeqNbr__c = 1;
        route.Account__C = objAc.id;
        //route.Schedule_Date__c = system.today();
        route.StopDate__c = System.today();
        // route.Sales_Rep__c = usr;
        insert route;  
        system.debug('route.Route__c.WSLRNbrRouteNbr__c=='+route.Route__r.WSLRNbrRouteNbr__c);
        system.debug('route=='+route);
         update objEve; 
     }
     
     static testMethod void UnitTest2() {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User usr1 = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '10500',
             WSLRNbrRouteNbr__c = '0D010093143'
             );
             insert usr1;
         
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
        account objAc = new account();
        objAc.name = 'Test Account';       
        objAc.recordtypeid = POCRtype.id;
        //objAc.billingCity = '';
        objAc.billingstate = 'THyderabad';
        //objAc.billingCountry = 'Hyderabad';
        //objAc.billingPostalCode = '500459';
        objAc.Trade_Program_NM__c = 'MACRO';
        //objAc.Wholesaler__c = objAcWhole.id;
        objAc.INDUS_VOL_CLASS_CD_US__c = '20';
        insert objAc;
        
        system.debug('objAc=='+objAc);
        
        event objEve  =  new event();
        objEve.subject = 'Test Event';
        objEve.Visit_in_Progress__c = false;
        objEve.Visit_Completed__c = true;
        objEve.OwnerId = usr1.id;
        objEve.Whatid = objAc.id;
        objEve.ActivityDateTime = system.today();
        objEve.DurationInMinutes = 30;
        objEve.Out_of_Range_on_End__c = false;
        //objEve.Out_of_Range_on_Start__c = true;
        //objEve.createddate = system.today();
        insert objEve;  
        
        objEve.Out_of_Range_on_Start__c = false;
        //objEve.createddate = system.today();
        //update objEve;
        
        string str = '0D010093143';
        Route__c objRte = new Route__c();
        objRte.WSLRNbrRouteNbr__c = str;      
        insert objRte; 
        
        system.debug('objRte=='+objRte);
        Route__c objRte3 = [select id,WSLRNbrRouteNbr__c from Route__c  where id =: objRte.id];
        system.debug('objRte3=='+objRte3);
        
        Route_Schedule__c route = new Route_Schedule__c();
        route.Route__c = objRte3.id;
        route.SeqNbr__c = 1;
        route.Account__C = objAc.id;
        //route.Schedule_Date__c = system.today();
        route.StopDate__c = System.today();
        // route.Sales_Rep__c = usr;
        insert route; 
        system.debug('route.Route__c.WSLRNbrRouteNbr__c=='+route.Route__r.WSLRNbrRouteNbr__c);
        system.debug('route=='+route);
        
        Route_Schedule__c rte2 = [select id,Route__c ,Route__r.WSLRNbrRouteNbr__c, Account__C from Route_Schedule__c where id =: route.id];
        system.debug('rte2 =='+rte2);
        system.debug('rte2route nbr =='+rte2.Route__r.WSLRNbrRouteNbr__c);
         System.debug('rte2 account =='+rte2.Account__c);
         update objEve;
     }
}