WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

WOD_Sprint11a_V1.1/objects/Account.object
    <fields>
        <fullName>Trade_Program_NM__c</fullName>
        <label>Trade Program NM</label>
        <length>100</length>
        <type>Text</type>
    </fields>

MOBcombined/objects/Account.object
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field displays the wholesaler that services this Retailer</inlineHelpText>
        <label>Wholesaler</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers Served</relationshipLabel>
        <relationshipName>Retailer_Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAPenhanceUATtoPROD0922/src/objects/US_Account_Target_Program__c.object
<CustomObject>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/classes/AB_Batch_Summarize_AssrtmntData_Test.cls
@isTest
public class AB_Batch_Summarize_AssrtmntData_Test{
    static testMethod void UnitTest() {
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
        account objAc = new account();
        objAc.name = 'Test Account';       
        objAc.recordtypeid = POCRtype.id;
        objAc.billingCity = 'Hyderabad';
        objAc.billingstreet = 'ttt\r\nHyderabad';
        objAc.billingCountry = 'Hyderabad';
        objAc.billingPostalCode = '500459';
        objAc.Trade_Program_NM__c = 'MACRO';
        objAc.RTL_SEG_NM_US__c = 'PACKAGE LIQUOR';
        //objAc.Wholesaler__c = objAcWhole.id;
        objAc.WSLR_NBR_US__c = '54554';
        objAc.WSLR_ASGND_CUST_NBR_US__c = '434343';
        insert objAc; 
        
        Route__c objRte2 = new Route__c();
        objRte2.WSLRNbrRouteNbr__c = '0D010093141';      
        insert objRte2;
              
        RouteCust__c objCust = new RouteCust__c();
        objCust.Route__c = objRte2.id;
        objCust.Account__c = objAc.id;
        objCust.WSLRNbrRouteNbr__c = '0D010093141';
        insert objCust;
        
        RouteCust__c objCust2 = new RouteCust__c();
        objCust2.Route__c = objRte2.id;
        objCust2.Account__c = objAc.id;
        objCust2.WSLRNbrRouteNbr__c = '0D010093141';
        insert objCust2;
        
        
        US_Account_Target_Program__c objAcTrgt6 = new US_Account_Target_Program__c();
        objAcTrgt6.Account__c=objAc.id;
        objAcTrgt6.Brand_Category__c = 'FMB';       
        insert objAcTrgt6;
        
        US_Account_Target_Program__c objAcTrg6 = new US_Account_Target_Program__c();
        objAcTrg6.Account__c=objAc.id;
        objAcTrg6.Brand_Category__c = 'FMB';
        insert objAcTrg6;
        
        Test.startTest();
       AB_Batch_Summarize_AssrtmntData c = new AB_Batch_Summarize_AssrtmntData();
       Database.executeBatch(c);
       Test.stopTest();
    }
}