WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>Account_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <description>M360 Purpose</description>
        <label>Account Team</label>
        <type>Checkbox</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

UserProvisin_Batches_fix+V1.2/classes/AB_AccountTeam_Test.cls
/*Code coverage for 
AB_AccountTeam,
AB_AccountTeamTrigger,
AB_SearchAndReplace2_Batch,
AB_SearchAndReplace_Batch*/

@isTest
public class AB_AccountTeam_Test {
    public static string accId;
    public static string UName;
    public static string routeId;

    static testMethod void myTest() {
       
        CollaborationGroup cb = new CollaborationGroup();
        cb.Name = 'Test CB';
        cb.CollaborationType = 'Public';
        insert cb;
        
       Recordtype rt = [select id from Recordtype where Recordtype.name = 'Wholesaler' limit 1];
       account objAc = new account();
       objAc.name = 'Test Account';
       objAc.recordtypeid = rt.id;
       objAc.WSLR_NBR_US__c = '93411';
       insert objAc;
       
       accId = objAc.id;
       Route__c objRoute = new Route__c();
       objRoute.WSLRNbrRouteNbr__c= 'Test123';
       insert objRoute;
       
       Route__c objRoute1 = new Route__c();
       objRoute1 .WSLRNbrRouteNbr__c= 'Test1234';
       insert objRoute1 ;
       
       routeId = objRoute.id;
       
       RouteCust__c objRouteCust = new RouteCust__c ();
       objRouteCust.WSLRNbrRouteNbr__c = 'Test123';
       objRouteCust.Account__c =accId;
       objRouteCust.Route__c = routeId;
       insert objRouteCust;
       
       
       system.debug('accId==test'+accId);
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
        User usr = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.liestonyyy@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             WSLRNbrRouteNbr__c = 'Test123'
             );
             insert usr;
            
            /* usr.WSLRNbrRouteNbr__c = 'Test1234'; 
             update usr; 
             
              usr.WSLRNbrRouteNbr__c = ''; 
              update usr; */
            
               
       User usr1 = new User(LastName = 'LIVESTON',
             FirstName='JASONh',
             Alias = 'jlivh',
             Email = 'jason.livestohhhn@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '93411'
             //WSLRNbrRouteNbr__c = 'Test123'
             );
             insert usr1;
             
             //ConnectApi.ChatterUsers.follow(null, usr1.id, objAc.id);
             EntitySubscription eSub1 = new EntitySubscription(ParentID = objAc.Id, SubscriberId = usr1.id);
             insert eSub1;
             
        usr1.Wholesaler_Number__c = '93411';
             usr1.WSLRNbrRouteNbr__c = '93411D0106'; 
             update usr1;
             
              usr1.WSLRNbrRouteNbr__c = ''; 
              update usr1; 
             
             list<user> lstUsers = new list<user>();
           lstUsers.add(usr);
        lstUsers.add(usr1);
           list<RouteCust__c> lstrcust = new list<RouteCust__c>();
           lstrcust.add(objRouteCust); 
           usr.Account_Team__c = true;
            update usr;
        
        //Database.executeBatch(new AB_SearchAndReplace2_Batch());//'Test123',usr.id
        //Database.executeBatch(new AB_Batch_AccountTeam());
        AB_Batch_AccountTeam sh1 = new AB_Batch_AccountTeam();      
        String sch = '0  00 1 3 * ?';
        system.schedule('Test', sch, sh1);
        
        Set<Id> setIds = new Set<Id>();
        setIds.add(usr.Id);
        setIds.add(usr1.Id);
        List<Id> listUserIds = new List<Id>();
        listUserIds.add(usr.Id);
        listUserIds.add(usr1.Id);
        List<String> lstWSRNums = new List<String>();
        lstWSRNums.add('93411');
        Test.startTest();
        //Database.executeBatch(new AB_SearchAndReplace_Batch());//'Test123',usr.id,'WSLRNbrRouteNbr'
        AB_SearchAndReplace_Batch sh2 = new AB_SearchAndReplace_Batch();      
        String sc3 = '0  00 1 3 * ?';
        system.schedule('Test1', sc3, sh2);
        
        Test.stopTest();
        AB_AccountTeam.deletefollow(setIds);
        //insert lstUsers;
        AB_AccountTeam.deleteAccountTeam(setIds);
           AB_AccountTeam.addAccountteamfromRouteCust(lstrcust);
           AB_AccountTeam.deleteAccountTeams(lstrcust);
        
        
        
    }
}