WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

MOB_360_2017_1a_V5/objects/Route__c.object
<CustomObject>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

MOB_360_2017_1a_V5/classes/AB_AccountTeam_Test.cls
@isTest
public class AB_AccountTeam_Test {
    public static string accId;
    public static string UName;
    public static string routeId;

    static testMethod void myTest() {
       
        
       Recordtype rt = [select id from Recordtype where Recordtype.name = 'Wholesaler' limit 1];
       account objAc = new account();
       objAc.name = 'Test Account';
       objAc.recordtypeid = rt.id;
       objAc.WSLR_NBR_US__c = '93411';
       insert objAc;
       
       accId = objAc.id;
       Route__c objRoute = new Route__c();
       objRoute.WSLRNbrRouteNbr__c= 'Test123';
       insert objRoute;
       
       Route__c objRoute1 = new Route__c();
       objRoute1 .WSLRNbrRouteNbr__c= 'Test1234';
       insert objRoute1 ;
       
       routeId = objRoute.id;
       
       RouteCust__c objRouteCust = new RouteCust__c ();
       objRouteCust.WSLRNbrRouteNbr__c = 'Test123';
       objRouteCust.Account__c =accId;
       objRouteCust.Route__c = routeId;
       insert objRouteCust;
       
       
       system.debug('accId==test'+accId);
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
        User usr = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.liestonyyy@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             WSLRNbrRouteNbr__c = 'Test123'
             );
             insert usr;
            
            /* usr.WSLRNbrRouteNbr__c = 'Test1234'; 
             update usr; 
             
              usr.WSLRNbrRouteNbr__c = ''; 
              update usr; */
            
               
       User usr1 = new User(LastName = 'LIVESTON',
             FirstName='JASONh',
             Alias = 'jlivh',
             Email = 'jason.livestohhhn@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '93411'
             //WSLRNbrRouteNbr__c = 'Test123'
             );
             insert usr1;
             
             //ConnectApi.ChatterUsers.follow(null, usr1.id, objAc.id);
             EntitySubscription eSub1 = new EntitySubscription(ParentID = objAc.Id, SubscriberId = usr1.id);
             insert eSub1;
             
             usr1.WSLRNbrRouteNbr__c = '93411D0106'; 
             update usr1;
             
              usr1.WSLRNbrRouteNbr__c = ''; 
              update usr1; 
             
             list<user> lstUsers = new list<user>();
           lstUsers.add(usr);
           list<RouteCust__c> lstrcust = new list<RouteCust__c>();
           lstrcust.add(objRouteCust); 
           //AB_AccountTeam.addAccountTeam(lstUsers);
           
           AB_AccountTeam.deleteAccountTeam(lstUsers);
           AB_AccountTeam.addAccountteamfromRouteCust(lstrcust);
           AB_AccountTeam.deleteAccountTeams(lstrcust);
    }
}