WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

WOD_Sprint11a_V1.1/objects/Account.object
    <fields>
        <fullName>Trade_Program_NM__c</fullName>
        <label>Trade Program NM</label>
        <length>100</length>
        <type>Text</type>
    </fields>

MOBcombined/objects/Account.object
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field displays the wholesaler that services this Retailer</inlineHelpText>
        <label>Wholesaler</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retailers Served</relationshipLabel>
        <relationshipName>Retailer_Wholesaler</relationshipName>
        <type>Lookup</type>
    </fields>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

WOD_Sprint_12b_V1.6/objects/ONTAP__Order__c.object
<CustomObject>
    <fields>
        <fullName>RAS_CustID__c</fullName>
        <description>This field is used for Strike Rate dashboard in Mobility 360 Application.</description>
        <label>RAS_CustID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RAS_OrderSource__c</fullName>
        <description>This field is used for Strike Rate dashboard in Mobility 360 Application.</description>
        <label>RAS_OrderSource</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RAS_WSLRNbrCustIDRouteNbr__c</fullName>
        <description>This field is used for Strike Rate dashboard in Mobility 360 Application.</description>
        <label>RAS_WSLRNbrCustIDRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/classes/ONTAP_OrderTrigger_TapwiserUpate_Test.cls
/* code coverage for AONTAP_OrderTrigger_TapwiserUpate*/

@isTest
public class ONTAP_OrderTrigger_TapwiserUpate_Test {
    static testmethod void UnitTest(){
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
        account objAc = new account();
        objAc.name = 'Test Account';       
        objAc.recordtypeid = POCRtype.id;
        objAc.billingCity = 'Hyderabad';
        objAc.billingstreet = 'ttt\r\nHyderabad';
        objAc.billingCountry = 'Hyderabad';
        objAc.billingPostalCode = '500459';
        objAc.Trade_Program_NM__c = 'MACRO';
        objAc.RTL_SEG_NM_US__c = 'PACKAGE LIQUOR';
        //objAc.WSLR_ASGND_CUST_NBR_US__c = '434343';
        //objAc.Wholesaler__c = objAcWhole.id;
        objAc.WSLR_NBR_US__c = '54554';
        objAc.WSLR_ASGND_CUST_NBR_US__c = '434343';
        insert objAc; 
       
        Route__c objRte2 = new Route__c();
        objRte2.WSLRNbrRouteNbr__c = '32323232';      
        insert objRte2;
       
        RouteCust__c objCust = new RouteCust__c();
        objCust.Route__c = objRte2.id;
        objCust.Account__c = objAc.id;
        objCust.WSLRNbrRouteNbr__c = '32323232';
        objCust.WSLRNbrCustIDRouteNbr__c = '434343';
        insert objCust;
        
        Recordtype RASRtype = [select id,name from Recordtype where SobjectType = 'ONTAP__Order__c' and name ='RAS'];
        system.debug('======='+RASRtype);
        ONTAP__Order__c OnTap = new ONTAP__Order__c();
        OnTap.RAS_OrderSource__c = 'tapwiser';
        OnTap.RAS_WSLRNbrCustIDRouteNbr__c = '434343';
        OnTap.RecordTypeId = RASRtype.id;
        OnTap.RAS_CustID__c = '67675';
        insert OnTap;
        //update OnTap;
    }
    static testmethod void UnitTest2(){
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
        account objAc = new account();
        objAc.name = 'Test Account';       
        objAc.recordtypeid = POCRtype.id;
        objAc.billingCity = 'Hyderabad';
        objAc.billingstreet = 'ttt\r\nHyderabad';
        objAc.billingCountry = 'Hyderabad';
        objAc.billingPostalCode = '500459';
        objAc.Trade_Program_NM__c = 'MACRO';
        objAc.RTL_SEG_NM_US__c = 'PACKAGE LIQUOR';
        //objAc.WSLR_ASGND_CUST_NBR_US__c = '434343';
        //objAc.Wholesaler__c = objAcWhole.id;
        objAc.WSLR_NBR_US__c = '54554';
        objAc.WSLR_ASGND_CUST_NBR_US__c = '67675';
        insert objAc; 
       
        Route__c objRte2 = new Route__c();
        objRte2.WSLRNbrRouteNbr__c = '32323232';      
        insert objRte2;
       
        RouteCust__c objCust = new RouteCust__c();
        objCust.Route__c = objRte2.id;
        objCust.Account__c = objAc.id;
        objCust.WSLRNbrRouteNbr__c = '32323232';
        objCust.WSLRNbrCustIDRouteNbr__c = '434343';
        insert objCust;
        
        Recordtype RASRtype = [select id,name from Recordtype where SobjectType = 'ONTAP__Order__c' and name ='RAS'];
        system.debug('======='+RASRtype);
        ONTAP__Order__c OnTap = new ONTAP__Order__c();
        OnTap.RAS_OrderSource__c = 'tapwiser';
        OnTap.RAS_WSLRNbrCustIDRouteNbr__c = '434343';
        OnTap.RecordTypeId = RASRtype.id;
        OnTap.RAS_CustID__c = '67675';
        insert OnTap;
        update OnTap;
    }
}