MOB_360_2017_1a_V6/objects/Acct_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>ACTUALS__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>ACTUALS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acct_TotYR_Actuals</relationshipLabel>
        <relationshipName>Acct_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_VOLUME__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>LY VOLUME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TARGET__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>TARGET</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Acct_TotYR_Actuals</label>
    <nameField>
        <label>Acct_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acct_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/classes/AB_AggregateResultIterator_ACC.cls
global class AB_AggregateResultIterator_ACC implements Iterator<AggregateResult> {
   AggregateResult [] results {get;set;}
   // tracks which result item is returned
   Integer index {get; set;} 
          
   global AB_AggregateResultIterator_ACC() {
      index = 0;
      // Fire query here to load the results
      String query = 'select sum(ACTUALS__c) Actual,sum(LY_Volume__c) Volume,sum(TARGET__c) Target,BrandGroupID__c,BrandGroupName__c,account__c from Acct_TotYR_Actuals__c where BrandGroupID__c != null and account__c != null and BrandGroupName__c != null and Date__c = this_month group by BrandGroupID__c,account__c,BrandGroupName__c limit 20000';
      
      results = Database.query(query);            
   } 
    
   global boolean hasNext(){ 
      return results != null && !results.isEmpty() && index < results.size(); 
   }    
    
   global AggregateResult next(){        
      return results[index++];            
   }       
}