MOB_360_2017_1a_V6/objects/Acct_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acct_TotYR_Actuals</relationshipLabel>
        <relationshipName>Acct_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Acct_TotYR_Actuals</label>
    <nameField>
        <label>Acct_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acct_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V6/objects/EventLog__c.object
<CustomObject>
    <description>To track the user action</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application name</description>
        <label>Application</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Holds the Url</description>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <displayFormat>EL{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AB_IQ_Enhancements_V.2_0/objects/EventLog__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Log Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <type>Lookup</type>
    </fields>

MOB_360_2017_1a_V7/objects/MOB_Sales_Volume_Account__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Accounts</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 sales volume purpose</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>MOB_Sales_Volume_Account</label>
    <nameField>
        <displayFormat>SVA{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MOB_360_2017_1a_V5/classes/AB_Batch_Acc_SalesVolume_Test.cls
/*Code coverage for AB_Batch_Acc_SalesVolume and AB_SVolumeBatches_Execution_Trg*/
@isTest
private class AB_Batch_Acc_SalesVolume_Test{

    static testmethod void test() {
        // The query used by the batch job.
        EventLog__c objEve = new EventLog__c();
        objEve.Application__c = 'Mob360';
        objEve.Event__c = 'AccountActualVolumeLoaded';
        insert objEve;
        
        Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
       
       account objAc = new account();
       objAc.name = 'Test Account';       
       objAc.recordtypeid = POCRtype.id;       
       insert objAc;
       
       account objAc2 = new account();
       objAc2.name = 'Test Account2';       
       objAc2.recordtypeid = POCRtype.id;       
       insert objAc2;
       
       Acct_TotYR_Actuals__c objact = new Acct_TotYR_Actuals__c();
       objact.BrandGroupID__c = '1234';
       objact.account__c = objAc.id;
       objact.BrandGroupName__c = 'Bud';
       objact.Date__c = system.today();
       insert objact;
       
       Acct_TotYR_Actuals__c objact2 = new Acct_TotYR_Actuals__c();
       objact2.BrandGroupID__c = '12345';
       objact2.account__c = objAc2.id;
       objact2.BrandGroupName__c = 'Bud LIGHT';
       objact2.Date__c = system.today();
       insert objact2;
        
       MOB_Sales_Volume_Account__c  obj1 = new MOB_Sales_Volume_Account__c();
       obj1.Account__c = objAc.id;
       obj1.BrandGroupID__c = '1234';
       obj1.Date__c = system.today();
       OBJ1.Brand_Category__c = 'Bud';
       insert obj1;
       
       
       
       Test.startTest();
       AB_Batch_Acc_SalesVolume c = new AB_Batch_Acc_SalesVolume();
       Database.executeBatch(c);
       Test.stopTest();

       
    }
}