MOB_360_2017_1a_V6/objects/Acct_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acct_TotYR_Actuals</relationshipLabel>
        <relationshipName>Acct_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Acct_TotYR_Actuals</label>
    <nameField>
        <label>Acct_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acct_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V6/objects/MOB_Sales_Volume_Route__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 Sales Volume dashboard purpose</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Routes</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MOB_Sales_Volume_Route</label>
    <nameField>
        <displayFormat>SVR{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M360_Sprint_01b_and_02a_V1.0/classes/AB_Batch_Route_SalesVolume_Test.cls
@isTest
private class AB_Batch_Route_SalesVolume_Test{

    static testmethod void test() {
       
       Route__c objRte2 = new Route__c();
       objRte2.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objRte2;
       
       Route__c objRte = new Route__c();
       objRte.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objRte;
       
       
       
       Recordtype POCRtype = [select id,name from Recordtype where SobjectType = 'Account' and name ='POC'];
       
       account objAc = new account();
       objAc.name = 'Test Account';       
       objAc.recordtypeid = POCRtype.id;       
       insert objAc;
       
       account objAc2 = new account();
       objAc2.name = 'Test Account2';       
       objAc2.recordtypeid = POCRtype.id;       
       insert objAc2;
       
       RouteCust__c objCust2 = new RouteCust__c();
       objCust2.Route__c = objRte.id;
       objCust2.Account__c = objAc.id;
       objCust2.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objCust2;
       
       RouteCust__c objCust = new RouteCust__c();
       objCust.Route__c = objRte.id;
       objCust.Account__c = objAc2.id;
       objCust.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objCust;
       
       Acct_TotYR_Actuals__c objact = new Acct_TotYR_Actuals__c();
       objact.BrandGroupID__c = '1234';
       objact.account__c = objAc.id;
       objact.BrandGroupName__c = 'Bud';
       objact.Date__c = system.today();
       insert objact;
       
       Acct_TotYR_Actuals__c objact3 = new Acct_TotYR_Actuals__c();
       objact3.BrandGroupID__c = '1234';
       objact3.account__c = objAc.id;
       objact3.BrandGroupName__c = 'Bud';
       objact3.Date__c = system.today();
       insert objact3;
       
       Acct_TotYR_Actuals__c objact2 = new Acct_TotYR_Actuals__c();
       objact2.BrandGroupID__c = '12345';
       objact2.account__c = objAc2.id;
       objact2.BrandGroupName__c = 'Bud LIGHT';
       objact2.Date__c = system.today();
       insert objact2;
        
       MOB_Sales_Volume_Route__c obj1 = new MOB_Sales_Volume_Route__c();
       obj1.Route__c = objRte2.id;
       obj1.BrandGroupID__c = '1234';
       obj1.Date__c = system.today();
       OBJ1.Brand_Category__c = 'Bud';
       insert obj1;
       
       
       
       Test.startTest();
       AB_Batch_Route_SalesVolume c = new AB_Batch_Route_SalesVolume();
       Database.executeBatch(c);
       Test.stopTest();

       
    }
}