MOB_360_2017_1a_V6/objects/Acct_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>ACTUALS__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>ACTUALS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acct_TotYR_Actuals</relationshipLabel>
        <relationshipName>Acct_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_VOLUME__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>LY VOLUME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TARGET__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>TARGET</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Acct_TotYR_Actuals</label>
    <nameField>
        <label>Acct_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acct_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V6/objects/EventLog__c.object
<CustomObject>
    <description>To track the user action</description>
    <label>EventLog</label>
    <nameField>
        <displayFormat>EL{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AB_IQ_Enhancements_V.2_0/objects/EventLog__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Log Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <type>Lookup</type>
    </fields>

MOB_360_2017_1a_V6/objects/MOB_Sales_Volume_Route__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 Sales Volume dashboard purpose</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_Volume__c</fullName>
        <label>LY Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Routes</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Route</label>
    <nameField>
        <displayFormat>SVR{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

M360_Sprint_02a_V1.3_2/objects/MOB_Sales_Volume_Route__c.object
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>M360 purpose - holds (route + BrandId + date)</description>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/classes/AB_Batch_Route_SalesVolume.cls
/*Author: Bharat*/
/*Description: Batch class to create MOB_Sales_Volume_Route__c when EventLog__c is created
               To get sales volume deshboard data*/ 

global class AB_Batch_Route_SalesVolume implements Database.Batchable<sobject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator([select ACTUALS__c,LY_Volume__c ,TARGET__c,BrandGroupID__c,BrandGroupName__c,Account__c from Acct_TotYR_Actuals__c where Date__c = this_month and BrandGroupID__c != null and BrandGroupName__c != null and Account__c  != null]);
   }
   
    global void execute(Database.BatchableContext BC, List<Acct_TotYR_Actuals__c> scope) {
        set<id> aid = new set<id>();
        list<RouteCust__c> lstRCusts = new list<RouteCust__c>();
        map<id,list<RouteCust__c>> mapRteAccts = new map<id,list<RouteCust__c>>();
        map<string,list<Acct_TotYR_Actuals__c>> mapRteActuals = new map<string,list<Acct_TotYR_Actuals__c>>();
        if(scope != null && !scope.isEmpty()){
        	for(Acct_TotYR_Actuals__c act : scope){
        		if(act.Account__c != null){
        			aid.add(act.Account__c);
        		}
        	}
        	if(!aid.isEmpty()){
	        	lstRCusts = [select id,Route__c, account__c from RouteCust__c where account__c in : aid];
	       		if(!lstRCusts.isEmpty()){
	       			for(RouteCust__c rte : lstRCusts){
	       				if(mapRteAccts.get(rte.Route__c) == null){
	       					list<RouteCust__c> lstRcsts = new list<RouteCust__c>();
	       					lstRcsts.add(rte);
	       					mapRteAccts.put(rte.Route__c,lstRcsts);
	       				}
	       				else{
	       					/*list<RouteCust__c> lstRcsts = new list<RouteCust__c>();
	       					lstRcsts.addAll(mapRteAccts.get(rte.Route__c));
	       					lstRcsts.add(rte);
	       					mapRteAccts.put(rte.Route__c,lstRcsts);*/
	       					list<RouteCust__c> lstRcsts = new list<RouteCust__c>();
	       					for(RouteCust__c rt : mapRteAccts.get(rte.Route__c)){
	       						if(rt.Account__c != rte.Account__c){
	       							lstRcsts.add(rte);
	       						}
	       					}
	       					lstRcsts.addAll(mapRteAccts.get(rte.Route__c));
	       					mapRteAccts.put(rte.Route__c,lstRcsts);
	       				}
	       			}
	       		}
        	}
        	if(mapRteAccts != null && !mapRteAccts.isEmpty()){
        		for(id rte : mapRteAccts.keyset()){
        			if(mapRteAccts.get(rte) != null){
		        		for(RouteCust__c rtCust : mapRteAccts.get(rte)){
		        			for(Acct_TotYR_Actuals__c act : scope){
		        				if(act.Account__c == rtCust.Account__c){
			        				string str = rtCust.Route__C+'-=-'+act.BrandGroupID__c+'-=-'+System.today().toStartOfMonth();
			        				if(mapRteActuals.get(str) == null){
			        					list<Acct_TotYR_Actuals__c> lstActuals = new list<Acct_TotYR_Actuals__c>();
			        					lstActuals.add(act);
			        					mapRteActuals.put(str,lstActuals);
			        				}
			        				else{
			        					list<Acct_TotYR_Actuals__c> lstActuals = new list<Acct_TotYR_Actuals__c>();
			        					lstActuals.addAll(mapRteActuals.get(str));
			        					lstActuals.add(act);
			        					mapRteActuals.put(str,lstActuals);
			        				}
		        				}
		        			}
		        		}
        			}
        		}
        	}
        	list<MOB_Sales_Volume_Route__c> lstMOBRoutes = new list<MOB_Sales_Volume_Route__c>();
        	if(!mapRteActuals.isEmpty()){
        		for(string str : mapRteActuals.keyset()){
        			decimal ActualSum = 0;
        			decimal VolumeSum = 0;
        			string bCategory = '';
        			if(mapRteActuals.get(str) != null){
	        			for(Acct_TotYR_Actuals__c actuals : mapRteActuals.get(str)){
	        				if(actuals.ACTUALS__c != null)
	        					ActualSum += actuals.ACTUALS__c;
	        		 		if(actuals.LY_Volume__c != null)
	        					VolumeSum += actuals.LY_Volume__c;
	        				if(actuals.BrandGroupName__c != null){
	        					bCategory = actuals.BrandGroupName__c;
	        				}
	        			}
        			}
        			list<string> strData = str.split('-=-');
        			MOB_Sales_Volume_Route__c objNewSV = new MOB_Sales_Volume_Route__c();
        			objNewSV.Actual_Volume__c = double.valueOf(ActualSum);
        			objNewSV.LY_Volume__c = double.valueOf(VolumeSum);
        			//objNewSV.Target_Volume__c = double.valueOf(objRute.get('Target'));
        			objNewSV.date__c = Date.today().toStartOfMonth();
        			objNewSV.BrandGroupID__c = strData[1];
        			objNewSV.Brand_Category__c = bCategory;        
        			objNewSV.Route__c = strData[0];
        			objNewSV.ExternalId__c = str;
        			lstMOBRoutes.add(objNewSV);
        		}
        	}
        	
        	try{
        		system.debug('lstMOBRoutes=='+lstMOBRoutes);
        		if(lstMOBRoutes != null && !lstMOBRoutes.isEmpty())
        			upsert lstMOBRoutes ExternalId__c;
        	}
        	catch(exception e) {
        		system.debug('DML Exception'+e);
        	}
        }
        
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}