MOB_360_2017_1a_V6/objects/MOB_Sales_Volume_Route__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 Sales Volume dashboard purpose</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Routes</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MOB_Sales_Volume_Route</label>
    <nameField>
        <displayFormat>SVR{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V7/objects/Route_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route_TotYR_Actuals</relationshipLabel>
        <relationshipName>Route_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route_TotYR_Actuals</label>
    <nameField>
        <label>Route_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V7/classes/AB_Batch_Route_SalesVolume_Test.cls
@isTest
private class AB_Batch_Route_SalesVolume_Test{

    static testmethod void test() {
       
       Route__c objRte2 = new Route__c();
       objRte2.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objRte2;
       
       Route__c objRte = new Route__c();
       objRte.WSLRNbrRouteNbr__c = 'usrNmbr';
       insert objRte;
       
       Route_TotYR_Actuals__c objact = new Route_TotYR_Actuals__c();
       objact.BrandGroupID__c = '1234';
       objact.Route__c = objRte2.id;
       objact.BrandGroupName__c = 'Bud';
       objact.Date__c = system.today();
       insert objact;
       
       Route_TotYR_Actuals__c objact2 = new Route_TotYR_Actuals__c();
       objact2.BrandGroupID__c = '12345';
       objact2.Route__c = objRte.id;
       objact2.BrandGroupName__c = 'Bud LIGHT';
       objact2.Date__c = system.today();
       insert objact2;
        
       MOB_Sales_Volume_Route__c obj1 = new MOB_Sales_Volume_Route__c();
       obj1.Route__c = objRte2.id;
       obj1.BrandGroupID__c = '1234';
       obj1.Date__c = system.today();
       OBJ1.Brand_Category__c = 'Bud';
       insert obj1;
       
       
       
       Test.startTest();
       AB_Batch_Route_SalesVolume c = new AB_Batch_Route_SalesVolume();
       Database.executeBatch(c);
       Test.stopTest();

       
    }
}