SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V7/objects/Route_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>ACTUALS__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>ACTUALS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_VOLUME__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>LY VOLUME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route_TotYR_Actuals</relationshipLabel>
        <relationshipName>Route_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TARGET__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>TARGET</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Route_TotYR_Actuals</label>
    <nameField>
        <label>Route_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V7/classes/AB_AggregateResultIterator_Routes.cls
global class AB_AggregateResultIterator_Routes implements Iterator<AggregateResult> {
   AggregateResult [] results {get;set;}
   // tracks which result item is returned
   Integer index {get; set;} 
          
   global AB_AggregateResultIterator_Routes() {
      index = 0;
      // Fire query here to load the results
      String query = 'select sum(ACTUALS__c) Actual,sum(LY_Volume__c) Volume,sum(TARGET__c) Target,BrandGroupID__c,BrandGroupName__c,Route__c from Route_TotYR_Actuals__c where Date__c = this_month and BrandGroupID__c != null and BrandGroupName__c != null and Route__c  != null group by BrandGroupID__c,Route__c,BrandGroupName__c limit 2000';
      results = Database.query(query);            
   } 
    
   global boolean hasNext(){ 
      return results != null && !results.isEmpty() && index < results.size(); 
   }    
    
   global AggregateResult next(){        
      return results[index++];            
   }       
}