M360_Sprint_01b_and_02a_V1.1/objects/AB_UserCreation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPointUrl__c</fullName>
        <label>EndPointUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clientSecret__c</fullName>
        <label>clientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <label>AB_UserCreation</label>
</CustomObject>

WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

MOBcombined/objects/Account.object
    <fields>
        <fullName>WSLR_NBR_US__c</fullName>
        <label>Wholesaler Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_User_Provisioning_V1.4_2017/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Global_User_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global User Only</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ALIAS__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>ALIAS</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>COMPANYNAME__c</fullName>
        <label>COMPANYNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>DEFAULTDIVISION__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>DEFAULTDIVISION</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMAILENCODINGKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>EMAILENCODINGKEY</label>
        <length>15</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMPLOYEE_NUMBER_US__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <externalId>true</externalId>
        <label>EMPLOYEE NUMBER US</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>FEDERATIONIDENTIFIER__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>FEDERATIONIDENTIFIER</label>
        <length>200</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ISACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ISACTIVE</label>
        <type>Checkbox</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LANGUAGELOCALEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LANGUAGELOCALEKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LOCALESIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LOCALESIDKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>NICKNAME__c</fullName>
        <label>NICKNAME</label>
        <length>50</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>PROFILEID__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>PROFILEID</label>
        <length>25</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ROUTEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ROUTEKEY</label>
        <length>13</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>TIMEZONEIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>TIMEZONEIDKEY</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>USERNAME__c</fullName>
        <description>ABIQ &amp; Mobility - created by nuvem</description>
        <label>USERNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>Username_Suffix__c</fullName>
        <description>This field is used for Contact to User creation trigger. Created by Nuvem.</description>
        <label>Username Suffix</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WHOLESALER_NUMBER__c</fullName>
        <description>M 360 purpose</description>
        <label>WHOLESALER NUMBER</label>
        <length>10</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <description>M360 Purpose</description>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>RouteKey__c</fullName>
        <description>the field is used as an identifier for mobility routes for sales routes</description>
        <label>RouteKey</label>
        <length>20</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>Send_To_Global__c</fullName>
        <defaultValue>false</defaultValue>
        <description>M_360 purpose - to send user to Global</description>
        <label>Send To Global</label>
        <type>Checkbox</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_User_Provisioning_V1.4_2017/classes/AB_CreateUserFromContact_Handler_Test.cls
/*
Auhtor Name : Nuvem Developer
Date        : Feb 3 2017
Description : Test class for create a user from a contact / Update user associated with contact when contact is updated
*/
@isTest
private class AB_CreateUserFromContact_Handler_Test {
    
    public static contact createCon(){
        Recordtype Rtype = [select id,name from Recordtype where SobjectType = 'contact' and name ='NAZ User'];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
       
        Contact objCon = new Contact();
        objCon.LastName =  'User';
        objCon.recordtypeid = Rtype.id;
        objCon.FirstName = 'Test';
        objCon.ALIAS__c = 'TestUser';
        objCon.Email = 'babitha.jampani@nuvemconsulting.com';
        objCon.MobilePhone = '9966784275';
        objCon.ISACTIVE__c = true;
        objCon.USERNAME__c = 'abiqtestuser@abiq.com';
        objCon.NICKNAME__C = 'abiq';
        objCon.PROFILEID__c = p.Id;
        objCon.COMPANYNAME__c = 'abiq';
        objCon.CurrencyIsoCode = 'USD';
        objCon.ROUTEKEY__c = '123456';
        objCon.Title = 'ABIQTitle';
        objCon.TIMEZONEIDKEY__c = 'GMT';
        objCon.LOCALESIDKEY__c = 'en_US';
        objCon.EMAILENCODINGKEY__c = 'ISO-8859-1';
        objCon.LANGUAGELOCALEKEY__c = 'en_US';
        objCon.DEFAULTDIVISION__c = '02dU0000000PAvHIAW';
        objCon.FEDERATIONIDENTIFIER__c = 'teskings986@nuvemconsulting.com';
        objCon.HE_Primary_Contact__c = true;
        objCon.WHOLESALER_NUMBER__c = '55';
        objCon.Username_Suffix__c = 'SuffixTest';
        objCon.EMPLOYEE_NUMBER_US__c = '0123';
        objCon.WSLRNbrRouteNbr__c = '0123434556';
        objCon.Global_User_Only__c=false;
        return objCon;
      
    }
    private Static testMethod void createContact()
    {
        AB_UserCreation__c objUC = new AB_UserCreation__c();
        objUC.Client_Id__c = 'clientId';
        objUC.clientSecret__c = 'ClSecret';
        objUC.username__c = 'uName';
        objUC.Password__c = 'pwd';
        objUC.EndPointUrl__c = 'testUrl';
        insert objUC;
        
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%WOD Lead%' Limit 1];
        User user1 = new User(
            Username = 'teskings986@test.com',
            ProfileId = portalProfile.Id,
            Alias = 'te986',
            Email = 'teskings986@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            FederationIdentifier = 'teskings986@nuvemconsulting.com'
            //Send_To_Global__c = true
        );
        Database.insert(user1);
        Account objAcc = new Account();
        objAcc.name = 'Test Account';
        objAcc.WSLR_NBR_US__c = '55';
        objAcc.Type = 'wholesaler';
        insert objAcc;
        
        createCon();
        List<Contact> lstCon = new List<Contact>();
        contact con=createCon();
        con.AccountId=objAcc.id;
        lstCon.add(con);
        INSERT lstCon;
        objAcc.WSLR_NBR_US__c = '6';
        update objAcc;
        con.WHOLESALER_NUMBER__c = '6';
        con.Department = 'Test Dept';
        con.Global_User_Only__c=true;
        con.ISACTIVE__c = true;
        update con;
    }
    
    private Static testMethod void createContact2(){
        AB_UserCreation__c objUC = new AB_UserCreation__c();
        objUC.Client_Id__c = 'clientId';
        objUC.clientSecret__c = 'ClSecret';
        objUC.username__c = 'uName';
        objUC.Password__c = 'pwd';
        objUC.EndPointUrl__c = 'testUrl';
        insert objUC;
        
        Account objAcc = new Account();
        objAcc.name = 'Test Account';
        objAcc.WSLR_NBR_US__c = '55';
        objAcc.Type = 'wholesaler';
        insert objAcc;
        
        createCon();
        List<Contact> lstCon = new List<Contact>();
        contact con=createCon();
        con.AccountId=objAcc.id;
        con.FEDERATIONIDENTIFIER__c = 'teskings987@nuvemconsulting.com';
        con.Email = 'babitha.jampani1@nuvemconsulting.com';
        con.Global_User_Only__c=false;
        con.ISACTIVE__c = true;
        lstCon.add(con);
        INSERT lstCon;
    
    }
    
     private Static testMethod void createContact3(){
        AB_UserCreation__c objUC = new AB_UserCreation__c();
        objUC.Client_Id__c = 'clientId';
        objUC.clientSecret__c = 'ClSecret';
        objUC.username__c = 'uName';
        objUC.Password__c = 'pwd';
        objUC.EndPointUrl__c = 'testUrl';
        insert objUC;
        
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%WOD Lead%' Limit 1];
        User user1 = new User(
            Username = 'teskings987@test.com',
            ProfileId = portalProfile.Id,
            Alias = 'te987',
            Email = 'teskings987@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            FederationIdentifier = 'teskings987@nuvemconsulting.com'
            //Send_To_Global__c = true
        );
        Database.insert(user1);
        Account objAcc = new Account();
        objAcc.name = 'Test Account';
        objAcc.WSLR_NBR_US__c = '55';
        objAcc.Type = 'wholesaler';
        insert objAcc;
        
        createCon();
        List<Contact> lstCon = new List<Contact>();
        contact con=createCon();
        con.AccountId=objAcc.id;
        con.FEDERATIONIDENTIFIER__c = 'teskings987@nuvemconsulting.com';
        con.Email = 'babitha.jampani2@nuvemconsulting.com';
        con.Global_User_Only__c=false;
        con.ISACTIVE__c = true;
        lstCon.add(con);
        INSERT lstCon;
        con.Global_User_Only__c=false;
        con.ISACTIVE__c = false;
        update con;
    
    }
    
     private Static testMethod void createContact4(){
        AB_UserCreation__c objUC = new AB_UserCreation__c();
        objUC.Client_Id__c = 'clientId';
        objUC.clientSecret__c = 'ClSecret';
        objUC.username__c = 'uName';
        objUC.Password__c = 'pwd';
        objUC.EndPointUrl__c = 'testUrl';
        insert objUC;
        
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%WOD Lead%' Limit 1];
        User user1 = new User(
            Username = 'teskings988@test.com',
            ProfileId = portalProfile.Id,
            Alias = 'te987',
            Email = 'teskings987@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            CommunityNickname = 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            FederationIdentifier = 'teskings988@nuvemconsulting.com'
            //Send_To_Global__c = true
        );
        Database.insert(user1);
        Account objAcc = new Account();
        objAcc.name = 'Test Account';
        objAcc.WSLR_NBR_US__c = '55';
        objAcc.Type = 'wholesaler';
        insert objAcc;
        
        createCon();
        List<Contact> lstCon = new List<Contact>();
        contact con=createCon();
        con.AccountId=objAcc.id;
        con.FEDERATIONIDENTIFIER__c = 'teskings988@nuvemconsulting.com';
        con.Email = 'babitha.jampani3@nuvemconsulting.com';
        con.Global_User_Only__c=false;
        con.ISACTIVE__c = true;
        lstCon.add(con);
        INSERT lstCon;
        con.Global_User_Only__c=false;
        con.ISACTIVE__c = true;
        update con;
    
    }
    
    public static testMethod void createContact5(){
        Recordtype Rtype = [select id,name from Recordtype where SobjectType = 'contact' and name ='NAZ User'];
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        AB_UserCreation__c objUC = new AB_UserCreation__c();
        objUC.Client_Id__c = 'clientId';
        objUC.clientSecret__c = 'ClSecret';
        objUC.username__c = 'uName';
        objUC.Password__c = 'pwd';
        objUC.EndPointUrl__c = 'testUrl';
        insert objUC;
        Contact objCon1 = new Contact();
        objCon1.LastName =  'User';
        objCon1.recordtypeid = Rtype.id;
        objCon1.FirstName = 'Test';
        objCon1.ALIAS__c = 'TestUser';
        objCon1.Email = 'babitha.jampani@nuvemconsulting.com';
        objCon1.MobilePhone = '9966784275';
        objCon1.ISACTIVE__c = false;
        objCon1.USERNAME__c = 'abiqtestuser@abiq.com';
        objCon1.NICKNAME__C = 'abiq';
        objCon1.PROFILEID__c = p.Id;
        objCon1.COMPANYNAME__c = 'abiq';
        objCon1.CurrencyIsoCode = 'USD';
        objCon1.ROUTEKEY__c = '123456';
        objCon1.Title = 'ABIQTitle';
        objCon1.TIMEZONEIDKEY__c = 'GMT';
        objCon1.LOCALESIDKEY__c = 'en_US';
        objCon1.EMAILENCODINGKEY__c = 'ISO-8859-1';
        objCon1.LANGUAGELOCALEKEY__c = 'en_US';
        objCon1.DEFAULTDIVISION__c = '02dU0000000PAvHIAW';
        objCon1.FEDERATIONIDENTIFIER__c = 'teskings986@nuvemconsulting.com';
        objCon1.HE_Primary_Contact__c = true;
        objCon1.WHOLESALER_NUMBER__c = '55';
        objCon1.Username_Suffix__c = 'SuffixTest';
        objCon1.EMPLOYEE_NUMBER_US__c = '0123';
        objCon1.WSLRNbrRouteNbr__c = '0123434556';
        objCon1.Global_User_Only__c=false;
        insert objCon1;
        
        Contact objCon2 = new Contact();
        objCon2.LastName =  'User';
        objCon2.recordtypeid = Rtype.id;
        objCon2.FirstName = 'Test';
        objCon2.ALIAS__c = 'TestUser';
        objCon2.Email = 'babitha.jampani@nuvemconsulting.com';
        objCon2.MobilePhone = '9966784275';
        objCon2.ISACTIVE__c = true;
        objCon2.USERNAME__c = 'abiqtestuser@abiq.com';
        objCon2.NICKNAME__C = 'abiq';
        objCon2.PROFILEID__c = p.Id;
        objCon2.COMPANYNAME__c = 'abiq';
        objCon2.CurrencyIsoCode = 'USD';
        objCon2.ROUTEKEY__c = '123456';
        objCon2.Title = 'ABIQTitle';
        objCon2.TIMEZONEIDKEY__c = 'GMT';
        objCon2.LOCALESIDKEY__c = 'en_US';
        objCon2.EMAILENCODINGKEY__c = 'ISO-8859-1';
        objCon2.LANGUAGELOCALEKEY__c = 'en_US';
        objCon2.DEFAULTDIVISION__c = '02dU0000000PAvHIAW';
        objCon2.FEDERATIONIDENTIFIER__c = 'teskings986@nuvemconsulting.com';
        objCon2.HE_Primary_Contact__c = true;
        objCon2.WHOLESALER_NUMBER__c = '55';
        objCon2.Username_Suffix__c = 'SuffixTest';
        objCon2.EMPLOYEE_NUMBER_US__c = '0123';
        objCon2.WSLRNbrRouteNbr__c = '0123434556';
        objCon2.Global_User_Only__c=true;
        insert objCon2;
        
        Contact objCon3 = new Contact();
        objCon3.LastName =  'User';
        objCon3.recordtypeid = Rtype.id;
        objCon3.FirstName = 'Test';
        objCon3.ALIAS__c = 'TestUser';
        objCon3.Email = 'babitha.jampani@nuvemconsulting.com';
        objCon3.MobilePhone = '9966784275';
        objCon3.ISACTIVE__c = false;
        objCon3.USERNAME__c = 'abiqtestuser@abiq.com';
        objCon3.NICKNAME__C = 'abiq';
        objCon3.PROFILEID__c = p.Id;
        objCon3.COMPANYNAME__c = 'abiq';
        objCon3.CurrencyIsoCode = 'USD';
        objCon3.ROUTEKEY__c = '123456';
        objCon3.Title = 'ABIQTitle';
        objCon3.TIMEZONEIDKEY__c = 'GMT';
        objCon3.LOCALESIDKEY__c = 'en_US';
        objCon3.EMAILENCODINGKEY__c = 'ISO-8859-1';
        objCon3.LANGUAGELOCALEKEY__c = 'en_US';
        objCon3.DEFAULTDIVISION__c = '02dU0000000PAvHIAW';
        objCon3.FEDERATIONIDENTIFIER__c = 'teskings986@nuvemconsulting.com';
        objCon3.HE_Primary_Contact__c = true;
        objCon3.WHOLESALER_NUMBER__c = '55';
        objCon3.Username_Suffix__c = 'SuffixTest';
        objCon3.EMPLOYEE_NUMBER_US__c = '0123';
        objCon3.WSLRNbrRouteNbr__c = '0123434556';
        objCon3.Global_User_Only__c=true;
        insert objCon3;
        
    
    }
    
}