M360_Sprint_01b_and_02a_V1.1/objects/AB_UserCreation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPointUrl__c</fullName>
        <label>EndPointUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clientSecret__c</fullName>
        <label>clientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <label>AB_UserCreation</label>
</CustomObject>

AB_User_Provisioning_V1.4_2017/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Global_User_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global User Only</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ALIAS__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>ALIAS</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>COMPANYNAME__c</fullName>
        <label>COMPANYNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>DEFAULTDIVISION__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>DEFAULTDIVISION</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMAILENCODINGKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>EMAILENCODINGKEY</label>
        <length>15</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMPLOYEE_NUMBER_US__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <externalId>true</externalId>
        <label>EMPLOYEE NUMBER US</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>FEDERATIONIDENTIFIER__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>FEDERATIONIDENTIFIER</label>
        <length>200</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ISACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ISACTIVE</label>
        <type>Checkbox</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LANGUAGELOCALEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LANGUAGELOCALEKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LOCALESIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LOCALESIDKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>NICKNAME__c</fullName>
        <label>NICKNAME</label>
        <length>50</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>PROFILEID__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>PROFILEID</label>
        <length>25</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ROLEID__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ROLEID</label>
        <length>25</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ROUTEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ROUTEKEY</label>
        <length>13</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>TIMEZONEIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>TIMEZONEIDKEY</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>USERNAME__c</fullName>
        <description>ABIQ &amp; Mobility - created by nuvem</description>
        <label>USERNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>Username_Suffix__c</fullName>
        <description>This field is used for Contact to User creation trigger. Created by Nuvem.</description>
        <label>Username Suffix</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>Username_Suffix_Global__c</fullName>
        <defaultValue>&apos;.globalSIT&apos;</defaultValue>
        <label>Username Suffix Global</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WHOLESALER_NUMBER__c</fullName>
        <description>M 360 purpose</description>
        <label>WHOLESALER NUMBER</label>
        <length>10</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <description>M360 Purpose</description>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>RouteKey__c</fullName>
        <description>the field is used as an identifier for mobility routes for sales routes</description>
        <label>RouteKey</label>
        <length>20</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>Username_Suffix_Global__c</fullName>
        <description>M 360 Purpose - To add suffix next to the username in Global org</description>
        <label>Username Suffix Global</label>
        <length>255</length>
        <type>Text</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_User_Provisioning_V1.4_2017/classes/ABS_UserCreation_RestAPI.cls
/*Author ; Deepthi*/
/*Test class: ABS_UserCreation_RestAPI_Test*/

public class ABS_UserCreation_RestAPI
{
   
    public static wrapContact ContactUserList;
    
    public static string createUser(set<Id> ContactIds)
    {
        List<contact> lstCons = new List<contact>();
        ContactUserList = new wrapContact();
        system.debug('ContactIds'+ContactIds);
        lstCons = [select id,EMPLOYEE_NUMBER_US__c,LastName,FirstName,Email,MobilePhone,ISACTIVE__c,DEFAULTDIVISION__c,
                   USERNAME__c,Username_Suffix__c,NICKNAME__C,ROLEID__c,PROFILEID__c,TIMEZONEIDKEY__c,LOCALESIDKEY__c,ROUTEKEY__c,
                   COMPANYNAME__c,FEDERATIONIDENTIFIER__c,Title,CurrencyIsoCode,EMAILENCODINGKEY__c,LANGUAGELOCALEKEY__c,ALIAS__c,
                   Username_Suffix_Global__c,Global_User_Only__c,WSLRNbrRouteNbr__c,WHOLESALER_NUMBER__c from contact where id IN:ContactIds];
        system.debug(lstCons );
        if(!lstCons.isEmpty())
        {
            for(contact objCon:lstCons)
            {
                conWrapper cons = new conWrapper();
                cons.LastName = objCon.LastName;
                cons.Firstname = objCon.FirstName;
                cons.Alias = objCon.ALIAS__c;
                cons.Email = objCon.Email;
                cons.MobilePhone = objCon.MobilePhone;
                cons.IsActive = objCon.ISACTIVE__c;
                cons.Username = objCon.USERNAME__c;
                cons.CommunityNickname = objCon.FEDERATIONIDENTIFIER__c;//NICKNAME__C
                cons.CompanyName = objCon.COMPANYNAME__c;
                cons.CurrencyIsoCode = objCon.CurrencyIsoCode;
                cons.DefaultDivision = objCon.DEFAULTDIVISION__c;
                cons.FederationIdentifier = objCon.FEDERATIONIDENTIFIER__c;
                cons.Title = objCon.Title;
                cons.DefaultCurrencyIsoCode = objCon.CurrencyIsoCode;
                cons.TimeZoneSidKey = objCon.TIMEZONEIDKEY__c;
                cons.LocaleSidKey = objCon.LOCALESIDKEY__c;
                cons.EmailEncodingKey = objCon.EMAILENCODINGKEY__c;
                cons.LanguageLocaleKey = objCon.LANGUAGELOCALEKEY__c;
                cons.Username_Suffix_Global = objCon.Username_Suffix_Global__c;
                cons.Global_User_Only=objCon.Global_User_Only__c;
                cons.Source_Suffix=objCon.Username_Suffix__c;
                cons.WSLRNbrRouteNbr=objCon.WSLRNbrRouteNbr__c;
                ContactUserList.conWrap.add(cons);
            }
        }
        system.debug('communityUserListIns=='+ContactUserList);
        String jsonstring = (String)JSON.serialize(ContactUserList);
        System.debug(jsonstring);                     
        string accessToken=ReturnAccessToken();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(Label.AB_UserCreation_Url);
        request.setMethod('PUT');
        request.setTimeOut(120000) ;
        request.setHeader('Content-Type', 'application/json');  
        request.setBody(jsonstring);
        system.debug(jsonstring);
        request.setHeader('Authorization', 'Bearer ' + accessToken);
        Http http = new Http();
        HttpResponse response = new HttpResponse();
        string calloutStatus='';
        if(!Test.isRunningTest()) {
            response = http.send(request);   
            if(response.getStatusCode()==200)
            {
                calloutStatus='Success';  
            }else{
                calloutStatus='Error';
            }
            system.debug(calloutStatus);
            system.debug(response);   
        } else {
            String str = '[{"Username" : "TestMethod0@tset.com", "Status" : false, "ErrorMessage" : "Error Occured -> DUPLICATE_USERNAME: Duplicate Username. The username already exists in this or another Salesforce organization."}, {"Username" : "TestMethod1@test.com", "Status" : true, "ErrorMessage" : ""}]';
            response.setBody(str);
            response.setStatusCode(200);
            response.setStatus('OK');
            calloutStatus='Success'; 
        } 
        return calloutStatus;
       
    }
    
   
    // method which retrives access token
    public static String ReturnAccessToken()
    {
        list<profile> pid=[select id from profile where name='System Administrator' limit 1];
        AB_UserCreation__c abuc = AB_UserCreation__c.getInstance(pid[0].id);
        string clientId= abuc.Client_Id__c;
        String clientSecret=abuc.clientSecret__c;
        string username=abuc.username__c;
        string password=abuc.Password__c;
        String reqbody = 'grant_type=password&client_id=' + clientId + '&client_secret=' + clientSecret + '&username=' + username + '&password=' + password;
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setBody(reqbody);
        req.setMethod('POST');
        req.setTimeout(120000);
        req.setEndpoint(abuc.EndPointUrl__c);
        HttpResponse res;
        if(!Test.isRunningTest()) {
            res = h.send(req);
        } else {
            res = ABS_UserCreation_RestAPI_Mock.mockAutheticate();
        }
        deserializeResponse resp1 = (deserializeResponse) JSON.deserialize(res.getbody(), deserializeResponse.class);
        System.debug('Body   '+res.getBody());
        system.debug(resp1.access_token);
        return resp1.access_token;
    }
    
    // warpper for access token 
    public class deserializeResponse
    {
        public String id;
        public String access_token;
    }
    // warpper for user and contact
    
    
    public class wrapContact
    {
        public list<conWrapper> conWrap;
        public wrapContact()
        {
            conWrap= new list<conWrapper>();
        }
    
    }
   
    
    public class conWrapper
    {
        public string LastName;
        public string Firstname; 
        public string Alias;
        public string Email;
        public string MobilePhone;
        public boolean IsActive;
        public string Username ;
        public string CommunityNickname;
        public string CompanyName;
        public string CurrencyIsoCode;
        public string DefaultDivision;
        public string FederationIdentifier;
        public string Title;
        public string DefaultCurrencyIsoCode;
        public string TimeZoneSidKey;
        public string LocaleSidKey;
        public string EmailEncodingKey;
        public string LanguageLocaleKey;
        public string Username_Suffix_Global;
        public boolean Global_User_Only;
        public string Source_Suffix;
        public string WSLRNbrRouteNbr;
    }
   
    

}