M360_Sprint_01b_and_02a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

MOB_360_2017_1a_V7/objects/User.object
    <fields>
        <fullName>Ordering_interface__c</fullName>
        <defaultValue>false</defaultValue>
        <description>M360 purpose</description>
        <label>Ordering interface</label>
        <type>Checkbox</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/classes/AB_UserDashboards_Service_Test.cls
@isTest
public class AB_UserDashboards_Service_Test{
    static testMethod void UnitTest() {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User usr1 = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             LocaleSidKey = 'en_US',
             Wholesaler_Number__c = '10500',
             Ordering_interface__c = true
             );
             insert usr1;
        AB_UserDashboards_Service.AB_UserDashboards_Service(null,null,null,null,usr1.username,true);
    }
}