M360_Sprint_01b_and_02a_V1.1/objects/User.object
<CustomObject>
    <fields>
        <fullName>M360_EndDayDate__c</fullName>
        <description>M360 purpose</description>
        <label>M360_EndDayDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Route__c</fullName>
        <description>M360 purpose - To store temporary route id with date selected by user from IOS device</description>
        <label>Temp Route</label>
        <length>45</length>
        <type>Text</type>
    </fields>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/classes/AB_EndDayDate_Service.cls
//Author: Bharat
  //Description: To store today date in user when he ends the day from IOS
  //Created date: Feb 22/2016
  //Modification History: 

@RestResource(urlMapping='/AB_EndDayDate_Service/*')
    global with sharing class AB_EndDayDate_Service{
        
        @HttpPost //Method name
        //Check for User Authentication based on UserName and Password from external system 
        global static ResponseWrapper AB_EndDayDate_Service(string username,boolean isLogout){
            
            String strStatusMsg = '';//Holds the status message
            Integer isSuccessRes;//Holds the success response '1' or '0'
            list<user> LogedinUser = new list<user>();
            try{       
                LogedinUser = [select id,M360_EndDayDate__c,Temp_Route__c from user where username =: username];
                if(LogedinUser != null){
                    if(isLogout == true){
                        LogedinUser[0].Temp_Route__c = '';
                    }
                    else{
                        LogedinUser[0].M360_EndDayDate__c = system.today();
                        LogedinUser[0].Temp_Route__c = '';
                    }
                    update LogedinUser[0];
                    strStatusMsg = 'Success.';
                    isSuccessRes = 1;
                }
            }
            catch(exception e) {strStatusMsg = AB_M360.EventLog(e);isSuccessRes = 0;}
            //system.debug('isSuccessRes=='+isSuccessRes);
            ResponseWrapper obj = new ResponseWrapper(isSuccessRes , strStatusMsg);//Initialising the object for wrapper class. This object returns response to the external system.
            system.debug('obj=='+obj);
             
            return obj;      
        }
        //Wrapper class to serialize response
        global class ResponseWrapper
        {
            public integer isSuccess {get;set;}//Holds success or failure status.
            public String Message {get;set;}//Status message to be sent as response             
            public ResponseWrapper(integer isSuccess,String Message)
            {
                this.isSuccess =isSuccess;
                this.Message = Message;
            }
        }
        
    }