Roxo_567_V3.1/objects/GSC_Mission_KPI_Map__c.object
<CustomObject>
    <fields>
        <fullName>Mission_ID__c</fullName>
        <label>Mission ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>GSC Mission KPI Map</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSC Mission KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Roxo-V6_12-28-2016/objects/US_Account_Target_Program__c.object
<CustomObject>
    <fields>
        <fullName>Missions_id__c</fullName>
        <description>Which hold the mission id</description>
        <label>Missions_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Roxo-V6_12-28-2016/classes/AB_AtpMissionIdUpdateTest.cls
/*Created Date : 21/12/2016
Discription  : Test class for Trigger to update mission id from GSC object to ATP*/
@isTest
private class AB_AtpMissionIdUpdateTest {
    static testMethod void myTest() {
        GSC_Mission_KPI_Map__c ObjGsc = new GSC_Mission_KPI_Map__c(name='Test Gsc', Mission_ID__c= '12345');
        insert ObjGsc; //Insert GSC Record
        system.debug('ObjGsc=Test='+ObjGsc.id);
        Account objAcc = new Account(Name='Test Account');
        insert objAcc;
        US_Account_Target_Program__c ObjAtp = new US_Account_Target_Program__c (Account__c = objAcc.Id,Missions_ID__c=ObjGsc.Mission_ID__c);
        insert ObjAtp; //Insert ATP Record
        ObjGsc.Mission_ID__c = '12487';
        update ObjGsc;
        ObjGsc.Mission_ID__c = '';
        update ObjGsc;
    }
}