AB_User_Provisioning_V1.4_2017/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Global_User_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global User Only</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ALIAS__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>ALIAS</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>COMPANYNAME__c</fullName>
        <label>COMPANYNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>DEFAULTDIVISION__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>DEFAULTDIVISION</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMAILENCODINGKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>EMAILENCODINGKEY</label>
        <length>15</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>EMPLOYEE_NUMBER_US__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <externalId>true</externalId>
        <label>EMPLOYEE NUMBER US</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>FEDERATIONIDENTIFIER__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>FEDERATIONIDENTIFIER</label>
        <length>200</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ISACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ISACTIVE</label>
        <type>Checkbox</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LANGUAGELOCALEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LANGUAGELOCALEKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>LOCALESIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>LOCALESIDKEY</label>
        <length>10</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>NICKNAME__c</fullName>
        <label>NICKNAME</label>
        <length>50</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>PROFILEID__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>PROFILEID</label>
        <length>25</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ROLEID__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ROLEID</label>
        <length>25</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>ROUTEKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - Created by Nuvem</description>
        <label>ROUTEKEY</label>
        <length>13</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>TIMEZONEIDKEY__c</fullName>
        <description>ABIQ &amp; Mobility 360 - created by nuvem</description>
        <label>TIMEZONEIDKEY</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>USERNAME__c</fullName>
        <description>ABIQ &amp; Mobility - created by nuvem</description>
        <label>USERNAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>Username_Suffix__c</fullName>
        <description>This field is used for Contact to User creation trigger. Created by Nuvem.</description>
        <label>Username Suffix</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/Contact.object
    <fields>
        <fullName>Username_Suffix_Global__c</fullName>
        <defaultValue>&apos;.globalSIT&apos;</defaultValue>
        <label>Username Suffix Global</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WHOLESALER_NUMBER__c</fullName>
        <description>M 360 purpose</description>
        <label>WHOLESALER NUMBER</label>
        <length>10</length>
        <type>Text</type>
    </fields>

AB_ContactUserCreationTrigger_V1.2/objects/Contact.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <description>M360 Purpose</description>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>RouteKey__c</fullName>
        <description>the field is used as an identifier for mobility routes for sales routes</description>
        <label>RouteKey</label>
        <length>20</length>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.1/objects/User.object
    <fields>
        <fullName>Username_Suffix_Global__c</fullName>
        <description>M 360 Purpose - To add suffix next to the username in Global org</description>
        <label>Username Suffix Global</label>
        <length>255</length>
        <type>Text</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

AB_User_Provisioning_V1.4_2017/classes/AB_Batch_RestUserCreation.cls
/*Author: Bharat*/
/*Description: */ 

/* Test class: ABS_UserCreation_RestAPI_Test*/

global class AB_Batch_RestUserCreation implements Database.Batchable<sobject>, Database.AllowsCallouts,Schedulable,Database.Stateful {//,Database.Stateful
    
    global set<id> setConIds = new set<id>();
    global set<Id> setIds = new set<Id>();
    global AB_Batch_RestUserCreation (set<id> conIds)
    {
        setConIds  = conIds;
    }
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
      Schema.DescribeSObjectResult d = Schema.SObjectType.contact;
      Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
      Schema.RecordTypeInfo rtByName =  rtMapByName.get('NAZ User');
      system.debug(rtByName.getRecordTypeId());
      
      return Database.getQueryLocator([select id,EMPLOYEE_NUMBER_US__c,LastName,FirstName,Email,MobilePhone,ISACTIVE__c,DEFAULTDIVISION__c,
                            USERNAME__c,Username_Suffix__c,NICKNAME__C,ROLEID__c,PROFILEID__c,TIMEZONEIDKEY__c,LOCALESIDKEY__c,ROUTEKEY__c,
                            COMPANYNAME__c,FEDERATIONIDENTIFIER__c,Title,CurrencyIsoCode,EMAILENCODINGKEY__c,LANGUAGELOCALEKEY__c,ALIAS__c,
                            Username_Suffix_Global__c,Global_User_Only__c,WSLRNbrRouteNbr__c,WHOLESALER_NUMBER__c from contact where id IN:setConIds and
                            RecordTypeId=:rtByName.getRecordTypeId()]);
        
    }
   
    global void execute(Database.BatchableContext BC, List<contact> scope)
    {
        system.debug('scope=='+scope);
        string status;
        if(scope != null && !scope.isEmpty()){
            for(contact obj : scope)
            {
                setIds.add(obj.id);
            }
            system.debug('setIds=='+setIds);
            if(setIds != null && !setIds.isEmpty())
                status=ABS_UserCreation_RestAPI.createUser(setIds);
            if(test.isRunningTest())
                status = 'Success';
            system.debug('Created Execute');
        }
    }
    global void execute(schedulablecontext sc){
        //Database.executeBatch(new AB_Batch_RestUserCreation());
    }
    
    global void finish(Database.BatchableContext BC) {
    
        
    }
}