M360-Sprint-01a_V1.4/objects/MOB_Sales_Volume_Account__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Accounts</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Challenge__c</fullName>
        <formula>((Target_Volume__c - Actual_Volume__c) / Sales_Days__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daily Challenge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Days__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Sales Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Account</label>
    <nameField>
        <displayFormat>SVA{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

M360-Sprint-01a_V1.4/objects/MOB_Sales_Volume_Route__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Challenge__c</fullName>
        <formula>(( Target_Volume__c - Actual_Volume__c )/ Sales_Days__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daily Challenge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Routes</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Days__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Sales Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Route</label>
    <nameField>
        <displayFormat>SVR{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WOD_Sprint_12b_V1.6/objects/ONTAP__Order__c.object
<CustomObject>
    <fields>
        <fullName>RAS_RouteNbr__c</fullName>
        <description>This field is used for Strike Rate dashboard in Mobility 360 Application.</description>
        <label>RAS_RouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RAS_SubmitDateTime__c</fullName>
        <description>This field is used for Strike Rate dashboard in Mobility 360 Application.</description>
        <label>RAS_SubmitDateTime</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>RouteNbr__c</fullName>
        <description>RouteNbr</description>
        <label>RouteNbr</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V5/objects/Route__c.object
    <fields>
        <fullName>Call_Route_Adherence__c</fullName>
        <description>This field is used in M360 application. It stores the Route Adherence target percentage which is displayed in M360 Sales Excellence dashboard.</description>
        <inlineHelpText>Fill in the target percentage number for Route Adherence.</inlineHelpText>
        <label>Call Route Adherence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>

MOB_360_2017_1a_V5/objects/Route__c.object
    <fields>
        <fullName>Strike_Rate_Adherence__c</fullName>
        <description>This field is used in M360 application. It stores the Strike Rate target percentage which is displayed in M360 Sales Excellence dashboard.</description>
        <inlineHelpText>Fill in the target percentage number for Strike Rate.</inlineHelpText>
        <label>Strike Rate Adherence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>

MOB_360_2017_1a_V5/objects/Route__c.object
    <fields>
        <fullName>Tapwiser_Adherence__c</fullName>
        <description>This field is used in M360 application. It stores the Tapwiser target percentage which is displayed in M360 Sales Excellence dashboard.</description>
        <inlineHelpText>Fill in the target percentage number for Tapwiser.</inlineHelpText>
        <label>Tapwiser Adherence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>

WOD_Sprint12a_V1.1/objects/Route_Schedule__c.object
<CustomObject>
</CustomObject>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route Schedules</relationshipLabel>
        <relationshipName>Route_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>RouteNbr__c</fullName>
        <label>RouteNbr</label>
        <length>8</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>SeqNbr__c</fullName>
        <label>SeqNbr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>StopDate__c</fullName>
        <label>StopDate</label>
        <type>Date</type>
    </fields>

SAP_V3ToProd_V2/objects/Route_Schedule__c.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

SAP_V3ToProd_V2/objects/User.object
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>

M360-Sprint-01a_V1.4/classes/AB_SalesExcellence_Dashboard_Test.cls
@isTest
public class AB_SalesExcellence_Dashboard_Test {
    public static string strJSONBody; 
    static string usrNmbr = '93411D0106';//[select WSLRNbrRouteNbr__c from user where id =: UserInfo.getUserId()].WSLRNbrRouteNbr__c;
    static testMethod void myTest() {
      // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
      
       Frequency__c objFreq = new Frequency__c(name = 'Test Frequency');
       insert objFreq;
       Recordtype rt = [select id from Recordtype where SobjectType = 'Account' limit 1];
       account objAc = new account();
       objAc.name = 'Test Account';
       objAc.recordtypeid = rt.id;
       objAc.Delivery_Frequency__c = objFreq.id;
        
       insert objAc;
       
       Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
       User usr = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             WSLRNbrRouteNbr__c = '93411D0106',
             LocaleSidKey = 'en_US'
             );
             insert usr;
       strJSONBody = '{\"username\":\"'+usr.Username+'\"}'; 
            
       Route__c objRte = new Route__c();
       objRte.WSLRNbrRouteNbr__c = usrNmbr;
       objRte.RouteNbr__c = 'TestR1';
       objRte.Call_Route_Adherence__c = 80;
       objRte.Tapwiser_Adherence__c=80;
       objRte.Strike_Rate_Adherence__c=40;
       insert objRte;
       
       Route_Schedule__c route = new Route_Schedule__c();
       route.Route__c = objRte.id;
       route.SeqNbr__c = 1;
       route.Account__C = objAc.id;
       route.RouteNbr__c = 'TestR1';
       //route.Schedule_Date__c = system.today();
       route.StopDate__c = System.today();
      // route.Sales_Rep__c = usr;
       insert route;
       
       Route_Schedule__c route2 = new Route_Schedule__c();
       route2.Route__c = objRte.id;
       route2.SeqNbr__c = 1;
       route2.Account__C = objAc.id;
       //route.Schedule_Date__c = system.today();
       route2.StopDate__c = System.today();
       route2.RouteNbr__c = 'TestR1';
      // route.Sales_Rep__c = usr;
       insert route2;
       
       ONTAP__Order__c objOrdr =  new ONTAP__Order__c();
       objOrdr.ONTAP__OrderAccount__c = objAc.id;
       //objOrdr.ONTAP__Account__c = objAc.id;
       objOrdr.RAS_RouteNbr__c = 'TestR1';
        objOrdr.OnCall_Account__c = objAc.id;
        objOrdr.Delivery_Date__c = system.today();
       objOrdr.RAS_SubmitDateTime__c = system.now();
       insert objOrdr;
       
       ONTAP__Order__c objOrdr2 =  new ONTAP__Order__c();
       objOrdr2.ONTAP__OrderAccount__c = objAc.id;
       //objOrdr2.ONTAP__Account__c = objAc.id;
       objOrdr2.RAS_RouteNbr__c = 'TestR1';
        objOrdr2.OnCall_Account__c = objAc.id;
        objOrdr2.Delivery_Date__c = system.today();
       objOrdr2.RAS_SubmitDateTime__c = system.now();
       insert objOrdr2;
       
       RouteCust__c objCust = new RouteCust__c();
       objCust.Route__c = objRte.id;
       objCust.Account__c = objAc.id;
       objCust.WSLRNbrRouteNbr__c = usr.WSLRNbrRouteNbr__c;
       insert objCust;
       
       
       MOB_Sales_Volume_Route__c objSVR =  new MOB_Sales_Volume_Route__c();
       objSVR.Actual_Volume__c = 300;
       objSVR.Brand_Category__c = 'ABI';
       objSVR.Target_Volume__c = 600;
       //objSVR.Daily_Challenge__c = 900;
       objSVR.Date__c = system.today();
       objSVR.Route__c = objRte.id;
       objSVR.Sales_Days__c = 98;
       insert objSVR;
       
       MOB_Sales_Volume_Account__c objSVA =  new MOB_Sales_Volume_Account__c();
       objSVA.Actual_Volume__c = 300;
       objSVA.Brand_Category__c = 'ABI';
       objSVA.Target_Volume__c = 600;
       //objSVA.Daily_Challenge__c = 900;
       objSVA.Date__c = system.today();
       objSVA.Account__c = objAc.id;
       objSVA.Sales_Days__c = 98;
       insert objSVA;
              
       event objEve  =  new event();
       objEve.subject = 'Test Event';
       objEve.Visit_Completed__c = true;
       objEve.Out_of_Range_on_Start__c = false;
       objEve.Out_of_Range_on_End__c = false;
       objEve.EndDateTime = system.today();
       objEve.OwnerId = usr.id;
       objEve.Whatid = objAc.id;
       objEve.ActivityDateTime = system.today();
       objEve.DurationInMinutes = 0;
       insert objEve;
       
       objEve.Out_of_Range_on_Start__c = true;
       objEve.Out_of_Range_on_End__c = true;
       update objEve;
      
       AB_SalesExcellence_Dashboard.AB_SalesExcellence_Dashboard();
       AB_SalesExcellence_Dashboard.UserDetailsWrapper objUserDets = new AB_SalesExcellence_Dashboard.UserDetailsWrapper(usr.Username,'','');
   }
   //method to code coverage of AB_salesExcelleceTrg triiger
   static testMethod void SalesExcTrgrTest() {
      // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
       Recordtype rt = [select id from Recordtype where SobjectType = 'Account' limit 1];
       account objAc = new account();
       objAc.name = 'Test Account';
       objAc.recordtypeid = rt.id;
       insert objAc;
       
       Route__c objRte = new Route__c();
       objRte.WSLRNbrRouteNbr__c = usrNmbr;
       insert objRte;
       
       Route_Schedule__c route = new Route_Schedule__c();
       route.Route__c = objRte.id;
       route.SeqNbr__c = 1;
       route.Account__C = objAc.id;
       //route.Schedule_Date__c = system.today();
       route.StopDate__c = System.today();
      // route.Sales_Rep__c = usr;
       insert route;
       Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
       User usr = new User(LastName = 'LIVESTON',
             FirstName='JASON',
             Alias = 'jliv',
             Email = 'jason.liveston@asdf.com',
             Username = 'jason.lieston@as.com',
             ProfileId = profileId.id,
             TimeZoneSidKey = 'GMT',
             LanguageLocaleKey = 'en_US',
             EmailEncodingKey = 'UTF-8',
             WSLRNbrRouteNbr__c = '93411D0106',
             LocaleSidKey = 'en_US'
             );
             insert usr;
       
       event objEve  =  new event();
       objEve.subject = 'Test Event';
       objEve.Visit_Completed__c = true;
       objEve.Out_of_Range_on_Start__c = true;
       objEve.Out_of_Range_on_End__c = true;
       objEve.EndDateTime = system.today();
       objEve.OwnerId = usr.id;
       objEve.Whatid = objAc.id;
       objEve.ActivityDateTime = system.today();
       objEve.DurationInMinutes = 0;
       insert objEve;
       
       objEve.Out_of_Range_on_Start__c = false;
       objEve.Out_of_Range_on_End__c = false;
       update objEve;
   }
}