M360-Sprint-01a_V1.4/objects/MOB_Sales_Volume_Account__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Accounts</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 sales volume purpose</description>
        <label>BrandGroupID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_Volume__c</fullName>
        <description>M360 Sales volume Dashboard purpose</description>
        <label>LY Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Days__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Sales Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Account</label>
    <nameField>
        <displayFormat>SVA{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

M360-Sprint-01a_V1.4/classes/AB_Batch_Acc_SalesVolume.cls
/*Author: Bharat*/
/*Description: Batch class to create MOB_Sales_Volume_Account__c when Account_TotYR_Actuals__c is created
               To get sales volume deshboard data*/

global class AB_Batch_Acc_SalesVolume implements Database.Batchable<AggregateResult> {//sObject
    
    global Iterable<AggregateResult> start(Database.batchableContext info){
        // just instantiate the new iterable here and return
        return new AB_AggregateResultIterable_ACC();
    }
   
    global void execute(Database.BatchableContext BC, List<AggregateResult> scope) {
        set<id> setAid = new set<id>();
        list<MOB_Sales_Volume_Account__c> listSVAccounts = new list<MOB_Sales_Volume_Account__c>();
        set<string> setBrands = new set<string>();
        system.debug('scope=='+scope);
        
         for(AggregateResult a : scope)
         {
             if(a.get('Account__c') != null)
             	setAid.add(string.valueOf(a.get('Account__c'))); 
             if(a.get('BrandGroupID__c') != null) 
             	setBrands.add(string.valueOf(a.get('BrandGroupID__c'))); 
             
         }
         //system.debug('mapActuals=='+mapActuals);
              
         system.debug('setAid=='+setAid);
                system.debug('setBrands=='+setBrands);
        set<string> SetSVAccGrpIds = new set<string>();
        set<string> setAccts = new set<string>();
        
        Date startOfMonth = Date.today().toStartOfMonth();
        if(setAid != null && setBrands != null)
            listSVAccounts = [select id,Account__c,Brand_Category__c,BrandGroupID__c,Actual_Volume__c,Target_Volume__c,Sales_Days__c from MOB_Sales_Volume_Account__c where Account__c in : setAid and BrandGroupID__c in : setBrands and Date__c =this_month];
        system.debug('listSVAccounts=='+listSVAccounts);
        delete listSVAccounts;
        
        list<MOB_Sales_Volume_Account__c> lstSVAccToInsert = new list<MOB_Sales_Volume_Account__c>();
        for(AggregateResult a : scope)
        {
        	if(a.get('Account__c') != null)
            	lstSVAccToInsert.add(Insertdata(a));
        }
        insert lstSVAccToInsert;
    }   
    public MOB_Sales_Volume_Account__c Insertdata(AggregateResult objAccAct){
        MOB_Sales_Volume_Account__c objNewSVAcc = new MOB_Sales_Volume_Account__c();
        objNewSVAcc.Actual_Volume__c = double.valueOf(objAccAct.get('Actual'));
        objNewSVAcc.LY_Volume__c = double.valueOf(objAccAct.get('Volume'));
        objNewSVAcc.Target_Volume__c = double.valueOf(objAccAct.get('Target'));
        objNewSVAcc.date__c = Date.today().toStartOfMonth();
        objNewSVAcc.BrandGroupID__c = string.valueOf(objAccAct.get('BrandGroupID__c'));
        objNewSVAcc.Brand_Category__c = string.valueOf(objAccAct.get('BrandGroupName__c'));
        objNewSVAcc.account__c = string.valueOf(objAccAct.get('account__c'));
        return objNewSVAcc;
        
    }
    global void finish(Database.BatchableContext BC) {
    }
}