M360-Sprint-01a_V1.4/objects/MOB_Sales_Volume_Account__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Accounts</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 sales volume purpose</description>
        <label>BrandGroupID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_Volume__c</fullName>
        <description>M360 Sales volume Dashboard purpose</description>
        <label>LY Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Days__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Sales Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Account</label>
    <nameField>
        <displayFormat>SVA{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

M360-Sprint-01a_V1.4/objects/MOB_Sales_Volume_Route__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>Actual_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Actual Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>M360 Sales Volume dashboard purpose</description>
        <label>BrandGroupID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Brand Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_Volume__c</fullName>
        <label>LY Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>MOB_Sales_Volume_Routes</relationshipLabel>
        <relationshipName>MOB_Sales_Volume_Routes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Days__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Sales Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Volume__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Target Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MOB_Sales_Volume_Route</label>
    <nameField>
        <displayFormat>SVR{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOB_Sales_Volume_Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MOB_360_2017_1a_V7/objects/Route_TotYR_Actuals__c.object
<CustomObject>
    <description>This object is used in Sales Volume dashboard calculation on M360 application.</description>
    <fields>
        <fullName>ACTUALS__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>ACTUALS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BrandGroupID__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandGroupName__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>BrandGroupName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LY_VOLUME__c</fullName>
        <description>This field is used in Sales Volume dashboard calculation on M360 application.</description>
        <label>LY VOLUME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Route_TotYR_Actuals</relationshipLabel>
        <relationshipName>Route_TotYR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route_TotYR_Actuals</label>
    <nameField>
        <label>Route_TotYR_Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route_TotYR_Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M360-Sprint-01a_V1.4/classes/AB_Batch_Route_SalesVolume.cls
/*Author: Bharat*/
/*Description: Batch class to create MOB_Sales_Volume_Route__c when Route_TotYR_Actuals__c is created
               To get sales volume deshboard data*/ 

global class AB_Batch_Route_SalesVolume implements Database.Batchable<AggregateResult> {
    /*global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select sum(ACTUALS__c) Actual,sum(LY_Volume__c) Volume,BrandGroupID__c,Route__c from Route_TotYR_Actuals__c where Date__c = this_month group by BrandGroupID__c,Route__c limit 2000';
        return Database.getQueryLocator(query);
    }*/
    global Iterable<AggregateResult> start(Database.batchableContext info){
        // just instantiate the new iterable here and return
        return new AB_AggregateResultIterable();
    }
   
    global void execute(Database.BatchableContext BC, List<AggregateResult> scope) {
    	set<id> setRid = new set<id>();
    	//list<MOB_Sales_Volume_Account__c> listSVAccounts = new list<MOB_Sales_Volume_Account__c>();
    	list<MOB_Sales_Volume_Route__c> listSVRouts = new list<MOB_Sales_Volume_Route__c>();
    	set<string> setBrands = new set<string>();
    	system.debug('scope=='+scope);
         for(AggregateResult a : scope)
         {
             setRid.add(string.valueOf(a.get('Route__c')));  
             setBrands.add(string.valueOf(a.get('BrandGroupID__c'))); 
             //SumActuals = +a.         
         }
        set<string> SetSVRteGrpIds = new set<string>();
        Date startOfMonth = Date.today().toStartOfMonth();
        list<MOB_Sales_Volume_Route__c> lstSVRteToInsert = new list<MOB_Sales_Volume_Route__c>();
        if(setRid != null && setBrands != null)
        	//listSVRouts = [select id,Account__c,Brand_Category__c,BrandGroupID__c,Actual_Volume__c,Target_Volume__c,Sales_Days__c from MOB_Sales_Volume_Account__c where Account__c in : setAid and BrandGroupID__c in : setBrands and Date__c =: startOfMonth];
        	listSVRouts = [select id,Route__c,Brand_Category__c,BrandGroupID__c,Actual_Volume__c,Target_Volume__c,Sales_Days__c from MOB_Sales_Volume_Route__c where Route__c in : setRid and BrandGroupID__c in : setBrands and Date__c =: startOfMonth];
        delete listSVRouts;
        
        //list<MOB_Sales_Volume_Route__c> lstSVRteToInsert = new list<MOB_Sales_Volume_Route__c>();
        for(AggregateResult a : scope)
        {
        	if(a.get('Route__c') != null)
            	lstSVRteToInsert.add(Insertdata(a));
        }
        insert lstSVRteToInsert;
    }   
    public MOB_Sales_Volume_Route__c Insertdata(AggregateResult objRute){
    	MOB_Sales_Volume_Route__c objNewSV = new MOB_Sales_Volume_Route__c();
    	objNewSV.Actual_Volume__c = double.valueOf(objRute.get('Actual'));
    	objNewSV.LY_Volume__c = double.valueOf(objRute.get('Volume'));
    	objNewSV.Target_Volume__c = double.valueOf(objRute.get('Target'));
    	objNewSV.date__c = Date.today().toStartOfMonth();
    	objNewSV.BrandGroupID__c = string.valueOf(objRute.get('BrandGroupID__c'));
    	objNewSV.Brand_Category__c = string.valueOf(objRute.get('BrandGroupName__c'));
    	
    	objNewSV.Route__c = string.valueOf(objRute.get('Route__c'));
    	return objNewSV;
    	
    }
    global void finish(Database.BatchableContext BC) {
    }
}