WOD_Sprint11a_V1.1/objects/User.object
<CustomObject>
</CustomObject>

GSC_Triggers+V1.0/objects/User.object
    <fields>
        <fullName>Remote_Survey_Vendor_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>M360 Purpose</description>
        <label>Remote Survey Vendor Enabled</label>
        <type>Checkbox</type>
    </fields>

MOB360%20UAT%2020161020/src/objects/User.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <label>Wholesaler Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>

AB_GSCTrgrs_V1.0/objects/Wholesaler_Role__c.object
<CustomObject>
    <fields>
        <fullName>Remote_Survey_Vendor_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>M360 Purpose</description>
        <label>Remote Survey Vendor Enabled</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

SAP_V3ToProd/objects/Wholesaler_Role__c.object
    <fields>
        <fullName>Role_ID_WSLR__c</fullName>
        <description>Salesforce Role ID used for lookup</description>
        <label>Role ID WSLR</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>

SAP_V3ToProd/objects/Wholesaler_Role__c.object
    <fields>
        <fullName>Role_Name_WSLR__c</fullName>
        <description>Role name for Role ID Lookup</description>
        <label>Role Name WSLR</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Wholesaler_Role__c.object
    <fields>
        <fullName>Wholesaler_Name__c</fullName>
        <description>Name of Wholesaler in Role ID Lookup</description>
        <label>Wholesaler Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Wholesaler_Role__c.object
    <fields>
        <fullName>Wholesaler_Number__c</fullName>
        <description>Wholesaler Number used for Role ID Lookup.</description>
        <label>Wholesaler Number</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>

AB_GSCTrgrs_V1.0/classes/AB_GSCTriggers_Test.cls
////code coverage for AB_GSC_Usr_Trg and AB_GSC_WsrRole_Trg
@isTest
public class AB_GSCTriggers_Test{
    //code coverage for AB_GSC_Usr_Trg
    static testMethod void AB_GSC_Usr_Trg_Test() {
    
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];        
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        list<userrole> rle = [select id,name from userrole limit 2];
        
        System.runAs (thisUser) {
            Wholesaler_Role__c objWR = new Wholesaler_Role__c();
            objWR.Name = 'testNm1';
            objWR.Wholesaler_Number__c = '98989';
            objWR.Wholesaler_Type__c = 'WOD';
            objWR.Role_ID_WSLR__c = rle[1].id;
            objWR.Role_Name_WSLR__c = rle[1].name;
            objWR.Wholesaler_Name__c = 'TestWsaler';
            insert objWR;
             
            User usr1 = new User(LastName = 'LIVESTON',
                 FirstName='JASON',
                 Alias = 'jliv',
                 Email = 'jason.liveston@asdf.com',
                 Username = 'jason.lieston@as.com',
                 ProfileId = profileId.id,
                 TimeZoneSidKey = 'GMT',
                 LanguageLocaleKey = 'en_US',
                 EmailEncodingKey = 'UTF-8',
                 LocaleSidKey = 'en_US',
                 Wholesaler_Number__c = '10500',
                 userRoleId = rle[0].id
                 );
                 insert usr1;
                 usr1.userRoleId = rle[1].id;
                 update usr1;
                               
           /*AB_Batch_GSCUsrToWRoleCreation sh2 = new AB_Batch_GSCUsrToWRoleCreation();      
            String sc3 = '0  00 1 3 * ?';
            system.schedule('Test1', sc3, sh2);*/
           
       }
    }
    
    //code coverage for AB_GSC_WsrRole_Trg
    static testMethod void AB_GSC_WRole_Trg_Test() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];  
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1]; 
        list<userrole> rle = [select id,name from userrole limit 2];
        System.runAs (thisUser) {
            Wholesaler_Role__c objWR = new Wholesaler_Role__c();
            objWR.Name = 'testNm1';
            objWR.Wholesaler_Number__c = '98989';
            objWR.Wholesaler_Type__c = 'WOD';
            objWR.Role_ID_WSLR__c = rle[1].id;
            objWR.Role_Name_WSLR__c = rle[1].name;
            objWR.Wholesaler_Name__c = 'TestWsaler';
            objWR.Remote_Survey_Vendor_Enabled__c = true;
            insert objWR;
            objWR.Remote_Survey_Vendor_Enabled__c = false;
            update objWR;
            
            User usr1 = new User(LastName = 'LIVESTON',
                 FirstName='JASON',
                 Alias = 'jliv',
                 Email = 'jason.liveston@asdf.com',
                 Username = 'jason.lieston@as.com',
                 ProfileId = profileId.id,
                 TimeZoneSidKey = 'GMT',
                 LanguageLocaleKey = 'en_US',
                 EmailEncodingKey = 'UTF-8',
                 LocaleSidKey = 'en_US',
                 Wholesaler_Number__c = '10500',
                 userRoleId = rle[1].id,
                 Remote_Survey_Vendor_Enabled__c = true
                 );
                 insert usr1;
            
           /* AB_Batch_GSCUsrToWRoleCreation abg= new AB_Batch_GSCUsrToWRoleCreation();
            database.executeBatch(abg);*/
           
        }
    }
    
    //code coverage for AB_GSC_WsrRole_Trg
    static testMethod void AB_GSC_WRole_Trg_Test2() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];  
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1]; 
        list<userrole> rle = [select id,name from userrole limit 2];
        System.runAs (thisUser) {
            Wholesaler_Role__c objWR = new Wholesaler_Role__c();
            objWR.Name = 'testNm1';
            objWR.Wholesaler_Number__c = '98989';
            objWR.Wholesaler_Type__c = 'WOD';
            objWR.Role_ID_WSLR__c = rle[1].id;
            objWR.Role_Name_WSLR__c = rle[1].name;
            objWR.Wholesaler_Name__c = 'TestWsaler';
            objWR.Remote_Survey_Vendor_Enabled__c = true;
            insert objWR;
            objWR.Role_ID_WSLR__c = rle[0].id;
            update objWR;
            
            User usr1 = new User(LastName = 'LIVESTON',
                 FirstName='JASON',
                 Alias = 'jliv',
                 Email = 'jason.liveston@asdf.com',
                 Username = 'jason.lieston@as.com',
                 ProfileId = profileId.id,
                 TimeZoneSidKey = 'GMT',
                 LanguageLocaleKey = 'en_US',
                 EmailEncodingKey = 'UTF-8',
                 LocaleSidKey = 'en_US',
                 Wholesaler_Number__c = '10500',
                 userRoleId = rle[0].id,
                 Remote_Survey_Vendor_Enabled__c = true
                 );
                 insert usr1;
            
            
        }
    }
}