M360_Sprint_02a_V1.3_2/objects/ABIQ_RouteAssortment__c.object
<CustomObject>
    <description>To summarize assortment data at Route level for historical reporting purposes.</description>
    <fields>
        <fullName>Brand_Category__c</fullName>
        <label>Brand Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliant__c</fullName>
        <label>Compliant</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>M360 Purpose</description>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Non_Compliant__c</fullName>
        <label>Non Compliant</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>ABIQ_RouteAssortments</relationshipLabel>
        <relationshipName>ABIQ_RouteAssortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ABIQ RouteAssortment</label>
    <nameField>
        <label>ABIQ RouteAssortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABIQ_RouteAssortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WOD_Sprint12a_V1.1/objects/Account.object
<CustomObject>
</CustomObject>

SAP_V3ToProd_V2/objects/Account.object
    <fields>
        <fullName>SAP_Channel__c</fullName>
        <formula>IF(OR( ISPICKVAL( RTL_SEG_NM_US__c ,&apos;BAR/NIGHTCLUB&apos;), 
ISPICKVAL( RTL_SEG_NM_US__c ,&apos;CLUB &apos;),
ISPICKVAL( RTL_SEG_NM_US__c ,&apos;CONCESSIONAIRE&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;GAMING&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;KAM IND ACCT OFF PREMISE&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;LODGING&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;OTHER ON-PREMISE&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;RECREATION&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;RESTAURANT&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;TRAVEL&apos;)),&apos;On Premise&apos;,IF(OR( ISPICKVAL( RTL_SEG_NM_US__c ,&apos;SUPERCNTR/MASS M&apos;), ISPICKVAL( RTL_SEG_NM_US__c ,&apos;SUPERMKT/GROC&apos;)), &apos;Large Format&apos;,IF(OR(ISPICKVAL( RTL_SEG_NM_US__c ,&apos;CONVENIENCE&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;DRUG&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;MILITARY&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;MILITARY EXPORT&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;OTHER OFF-PREMISE&apos;),ISPICKVAL( RTL_SEG_NM_US__c ,&apos;PACKAGE LIQUOR&apos;)), &apos;Small Format&apos;, &apos;&apos;) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Channel</label>
        <type>Text</type>
    </fields>

SAPenhanceUATtoPROD0922/src/objects/Account.object
    <fields>
        <fullName>SAP_Color__c</fullName>
        <formula>IF(Account_Targets_Count__c =  SAP_Color_Indicator_from_ATP__c, &apos;Green&apos;,
IF(Account_Targets_Count__c =  -1*SAP_Color_Indicator_from_ATP__c, &apos;Red&apos;,&apos;Yellow&apos; 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Color</label>
        <type>Text</type>
    </fields>

SAP_V3ToProd/objects/Route__c.object
<CustomObject>
    <description>Routes</description>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <externalId>true</externalId>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Routes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAP_V3ToProd/objects/RouteCust__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>RouteCust</relationshipLabel>
        <relationshipName>RouteCust</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSLRNbrRouteNbr__c</fullName>
        <label>WSLRNbrRouteNbr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RouteCust</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>RouteCust ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteCust</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAPenhanceUATtoPROD0922/src/objects/US_Account_Target_Program__c.object
<CustomObject>
</CustomObject>

Roxo_567_V3/objects/US_Account_Target_Program__c.object
    <fields>
        <fullName>Pannel_Color__c</fullName>
        <description>Panel Color formula</description>
        <formula>IF(SAP_Color_Indicator__c &gt; 0, &apos;Greencircle&apos;,  IF(SAP_Color_Indicator__c &lt; 0, &apos;Redcircle&apos;, &apos;Redcircle&apos;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pannel Color</label>
        <type>Text</type>
    </fields>

M360_Sprint_01b_and_02a_V1.0/classes/AB_Batch_Summarize_AssrtmntData.cls
global class AB_Batch_Summarize_AssrtmntData implements Database.batchable<sObject>{ 
   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator([select id,WSLRNbrRouteNbr__c,Route__c,Account__r.name,Account__c,Account__r.SAP_Color__c from RouteCust__c where Account__c != null and Route__c != null]);// or id in:accountId
   }

   global void execute(Database.BatchableContext BC, List<RouteCust__c> scope){
   system.debug('scope=='+scope);
   system.debug('scope=='+scope.SIZE());
       map<id,RouteCust__c > MapRtCsts = new map<id,RouteCust__c >();
        map<id,list<id>> MapRtes = new map<id,list<id>>();
        map<id,list<US_Account_Target_Program__c>> mapAccTgtPgms = new map<id,list<US_Account_Target_Program__c>>();
        set<id> setAids = new set<id>();
        for(RouteCust__c obj : scope){
            //system.debug(obj.Route__c);
            //system.debug(obj.Account__c);
            setAids.add(obj.Account__c);
            if(MapRtes.get(obj.Route__c)==null ){
                        
                list<id> lstAccs = new list<id>();
                lstAccs.add(obj.Account__c);
                MapRtes.put(obj.Route__c,lstAccs);
                //system.debug('=========mapAccTgtPgms');
            }else{
            
                list<id> lstAccs = new list<id>();
                lstAccs.addall(MapRtes.get(obj.Route__c));
                lstAccs.add(obj.Account__c);
                MapRtes.put(obj.Route__c,lstAccs);
                //system.debug('=========mapAccTgtPgms');
            }
            MapRtCsts.put(obj.Route__c,obj);
        } 
        
        /*START: Getting US_Account_Target_Program__c data*/
        
        list<US_Account_Target_Program__c> lstAccTgtPgms = new list<US_Account_Target_Program__c>();
        if(setAids != null)
            lstAccTgtPgms = [select id, Pannel_Color__c,Account__c,Account__r.SAP_Channel__c, Brand_Category__c,Achieved_Targets__c,Program_Target_Level__c from US_Account_Target_Program__c where Account__c in: setAids and Brand_Category__c != null];  
        if(lstAccTgtPgms != null && !lstAccTgtPgms.isEmpty())
        {
            for(US_Account_Target_Program__c objTgt : lstAccTgtPgms){
                if(mapAccTgtPgms.get(objTgt.Account__c)==null ){
                        
                   list<US_Account_Target_Program__c> lstTgts = new list<US_Account_Target_Program__c>();
                   lstTgts.add(objTgt);
                    mapAccTgtPgms.put(objTgt.Account__c,lstTgts);
                    //system.debug('=========mapAccTgtPgms');
                }else{
                
                    list<US_Account_Target_Program__c> lstTgts = new list<US_Account_Target_Program__c>();
                    lstTgts.addall(mapAccTgtPgms.get(objTgt.Account__c));
                    lstTgts.add(objTgt);
                    mapAccTgtPgms.put(objTgt.Account__c,lstTgts);
                    //system.debug('=========mapAccTgtPgms');
                }
            }
        }
        /*END: Getting US_Account_Target_Program__c data*/
        
        
        map<string,ABIQ_RouteAssortment__c> mapRAsrts = new map<string,ABIQ_RouteAssortment__c>();       
        ABS_SapScore newClass = new ABS_SapScore();
        list<ABIQ_RouteAssortment__c> lstRAsrtsToInsrt = new list<ABIQ_RouteAssortment__c>();
        list<ABIQ_RouteAssortment__c> lstRAsrtsToUpdt = new list<ABIQ_RouteAssortment__c>();
        list<id> Routeids = new list<id>();
        for(id Rid : MapRtes.keyset()){
            //ABIQ_RouteAssortment__c objRAsrt = new ABIQ_RouteAssortment__c();
            //objRAsrt.Route__c = Rid;
            
            for(id objACCid : MapRtes.get(Rid)){
                
                if(mapAccTgtPgms.get(objACCid) != null){
                    for(US_Account_Target_Program__c objTgtpgms : mapAccTgtPgms.get(objACCid)){
                    
                        /*Start: new code***********************************************************/
                        string str = Rid+'-=-'+objTgtpgms.Brand_Category__c+'-=-'+System.today().toStartOfMonth();
                        if(mapRAsrts.get(str) != null){
                            system.debug('mapRAsrts.get(str)=='+mapRAsrts.get(str));
                            if(objTgtpgms.Pannel_Color__c != null && objTgtpgms.Pannel_Color__c.equalsIgnoreCase('Redcircle'))
                                mapRAsrts.get(str).Compliant__c +=1;
                            if(objTgtpgms.Pannel_Color__c != null && objTgtpgms.Pannel_Color__c.equalsIgnoreCase('Greencircle'))
                                 mapRAsrts.get(str).Non_Compliant__c +=1;
                            mapRAsrts.get(str).ExternalId__c = str;
                            system.debug('Update=='+str);
                        }
                        else{
                            ABIQ_RouteAssortment__c ABIQ_Rasrt = new ABIQ_RouteAssortment__c();
                            ABIQ_Rasrt.Route__c = Rid;
                            ABIQ_Rasrt.Brand_Category__c = objTgtpgms.Brand_Category__c;
                            if(objTgtpgms.Pannel_Color__c != null && objTgtpgms.Pannel_Color__c.equalsIgnoreCase('Redcircle'))
                                ABIQ_Rasrt.Compliant__c = 1;
                            else
                                ABIQ_Rasrt.Compliant__c = 0;
                            if(objTgtpgms.Pannel_Color__c != null && objTgtpgms.Pannel_Color__c.equalsIgnoreCase('Greencircle'))
                                ABIQ_Rasrt.Non_Compliant__c = 1;
                            else
                                ABIQ_Rasrt.Non_Compliant__c = 0;
                            ABIQ_Rasrt.Month__c = System.today().toStartOfMonth();
                            ABIQ_Rasrt.ExternalId__c = str;
                            mapRAsrts.put(str,ABIQ_Rasrt);
                            system.debug('Insert=='+str);
                            
                        }
                        /*Stop: new code***********************************************************/
                        
                        
                        
                    }
                }
            }
        }    
        list<ABIQ_RouteAssortment__c> lstUpsert = new list<ABIQ_RouteAssortment__c>();
        if(mapRAsrts != null){
            for(ABIQ_RouteAssortment__c objRAsrt : mapRAsrts.values()){
                lstUpsert.add(objRAsrt);
            }
            
        }
        try{
            //insert lstRAsrtsToInsrt;
            //update lstRAsrtsToUpdt;
            //delete lstExistRAsrts;
            //insert lstUpsert;
            system.debug('lstUpsert=='+lstUpsert);    
            system.debug('lstUpsert=='+lstUpsert.size());
            if(lstUpsert != null && !lstUpsert.isEmpty())
           		upsert lstUpsert ExternalId__c;
           
               
        }
        catch(Exception e){
            system.debug('Dml Exception'+ e);
        }
   }

   global void finish(Database.BatchableContext BC){
   }
}